### ISSUE TITLE
Reconsider `lab_meta_data` section of ophys files

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/OpenScopeNWB#100]
the `lab_meta_data` section isn't standard with the NWB. It also contains information that is either redundant, unnecessary, or should probably belong elsewhere in the file like `acquisition`. Should we redo the way this information is packaged?

**Comment by Ahad-Allen** [comment]
The lab meta data is part of the standard, I think? https://nwb-schema.readthedocs.io/en/latest/format.html#sec-labmetadata. Though, I notice the dandi schema doesn't have underscores, so maybe that needs to be fixed.

**Comment by rcpeene** [comment]
Ah well I must have spoke too soon! We should have a discussion as to what information we want to include in here.

**Comment by jeromelecoq** [comment]
So we need to create a ticket to fill group image place holders for mesocope
