### ISSUE TITLE
Redundant optotagging fields?

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/OpenScopeNWB#102]
I discovered that in the visual coding files, and our own with optotagging, there are a few fields;
- `nwb.processing["optotagging"]["optogenetic_stimulation"]`, which is the optogenetic stim table
- `nwb.processing["optotagging]["optotagging"].data` 
- `nwb.processing["optotagging]["optotagging"].timestamps`

The latter two contain the duration of each pulse and the timestamps of each pulse respectively, but the optogenetic stimulus table has columns `duration` and `start_time` which contain the identical data. This is redundant data storage. It's not a super big deal  in terms of storage because they have only 600 elements, but this is another idiosyncracy which slightly confounds our files. However, there could be a good reason for this. Should we do anything, or leave it be?

**Comment by rcpeene** [comment]
Perhaps relevant, there's also this data structure which might be useful for storing this information. https://pynwb.readthedocs.io/en/stable/pynwb.ogen.html which doesn't appear to be used right now.

**Comment by Ahad-Allen** [comment]
Ben suggested switching to the optogenetic series in place of timeseries. I am currently generating a file using that to see if there will be any errors. We have also reached to severine for the relevant metadata info.

**Comment by Ahad-Allen** [comment]
I had some challenges while converting, but the most recent error I've run into is: 
`hdmf.build.errors.OrphanContainerBuildError: optotagging (optotagging): Linked OptogeneticStimulusSite 'OptogeneticStimulusSite' has no parent. Remove the link or ensure the linked container is added properly.`
I think this problem is because the stimulussite was not being added to the nwb file using the add_ogen_site function, I am trying a conversion with that method now.

**Comment by Ahad-Allen** [comment]
Tracked with: https://github.com/AllenInstitute/AllenSDK/issues/2680

**Comment by Ahad-Allen** [comment]
I've scheduled a meeting with Adam on Wednesday to discuss how to handle the SDK issues and making PRs for all these unrelated tickets :)

**Comment by Ahad-Allen** [comment]
Sent some newly generated files to Carter for review.

**Comment by jeromelecoq** [comment]
We need to update a list of NWB files to the new standards (both illusion and glow datasets). 
1. @Ahad-Allen to write email to notice the team with deadline. 
2. When agreement, trigger conversion and re-upload. 
3. Re-do BarCoding files with new convention.

**Comment by jeromelecoq** [comment]
This was confirmed done
