### ISSUE TITLE
NWB Rename code only triggers for one experiment per session.

### ISSUE THREAD

**Issue by Ahad-Allen** [AllenInstitute/OpenScopeNWB#103]
While the ophys rename code ran and succesfully renamed the files within the dandiset for dendritic coupling, it seems to have only done this for one experiment per session. https://dandiarchive.org/dandiset/000336/draft/files?location=, this isn't true for sub-1199275030, which makes me think this might be caused by a timeout error or something not related to an error with the for loop. I am looking into this now.

**Comment by Ahad-Allen** [comment]
Ah, the code returned an error of: urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) over the weekend. I am looking into what could be causing the code to throw this error.

**Comment by jeromelecoq** [comment]
We think this might be the code going touching rate limiting. Perhaps adding a sleep to the code to avoid touching the limit.

**Comment by Ahad-Allen** [comment]
I added a sleep and have rerun the code.

**Comment by Ahad-Allen** [comment]
Ah, there is one other issue going on here. As you can see here, the code has run properly and generated a file for each session of a subject. 


![Image](https://user-images.githubusercontent.com/87045911/220170113-6c5c92f9-9d8d-4ce9-9af7-06d70d7b964d.png)

The problem is, there is no identifier for EXPERIMENT ids, so the code automatically overrides each experiment with the next experiment from the session when that experiment's upload is triggered! The way other projects, like the credit assignment have handled this is adding the timestamp to the file name (Jerome is probably more familiar with this since he worked on these uploads just recently)


![Image](https://user-images.githubusercontent.com/87045911/220170434-47175047-06e2-4961-8530-676c68546430.png)

I wonder if this is the best way to do this, as it will make searching by experiment quite difficult. I am going to reach out to the dandi team to see if there is a good way to handle this.

**Comment by Ahad-Allen** [comment]
The best way to handle this is merely adding the exp-id to the sess-id string. Not an issue and be handled with the regen of the files

**Comment by Ahad-Allen** [comment]
The regen of files based on the dendrite team's request is trakced with #105

**Comment by Ahad-Allen** [comment]
This issue in particular has been fixed, I have also filed an issue about adding specific keys for the experiment ids and the raw flag for larger files here: https://github.com/dandi/dandi-cli/issues/1235
