### ISSUE TITLE
Regen Ophys Files using dendrite team's meta-data requests

### ISSUE THREAD

**Issue by Ahad-Allen** [AllenInstitute/OpenScopeNWB#105]
The dendrite team wanted some changes to the subject field of the dendrite coupling files. Primarily, they want the 6 digit mouse id added into the file name, in addition to the subject and session ids. This is because they want to use this id to help match to planes from the stacks they recieve. Because of this, the old sessions need to be regenerated using my updated Script. I have started one to see how the process goes and can trigger the rest if it works :)

**Comment by jeromelecoq** [comment]
Add specimen id on data portal. Also explain in column tooltip what is the difference between specimen id and mouse id.

**Comment by Ahad-Allen** [comment]
I have shared a test release with the dendrite team and they are looking over the table on the data portal. They seem to be finding it useful, but I am just waiting for some final feedback to close.
