### ISSUE TITLE
Test Dendrite Sessions which have a 'stuck' processing step

### ISSUE THREAD

**Issue by Ahad-Allen** [AllenInstitute/OpenScopeNWB#107]
The processing queue of the dendrite sessions seems to be failing at DF_OVER_F_COMPUTATION_V2_QUEUE causing the sessions to be stuck in the processing phase. Shiella sent me a list of sessions which should otherwise be ok to try and see if they're still ok for conversion

**Comment by Ahad-Allen** [comment]
Session 125416118 is currently being tested, I will update this ticket with the results of the conversion.

**Comment by jeromelecoq** [comment]
Related thread : 

They’ve all been set to rerun.
 
From: Mike Huang <[mike.huang@alleninstitute.org](mailto:mike.huang@alleninstitute.org)> 
Sent: Monday, March 20, 2023 1:48 PM
To: Zeb Haradon <[zebh@alleninstitute.org](mailto:zebh@alleninstitute.org)>; Chris Morrison <[chris.morrison@alleninstitute.org](mailto:chris.morrison@alleninstitute.org)>; Pika <[Pika@AllenInstitute.onmicrosoft.com](mailto:Pika@AllenInstitute.onmicrosoft.com)>
Cc: Jerome Lecoq <[jeromel@alleninstitute.org](mailto:jeromel@alleninstitute.org)>; Peter Groblewski <[peterg@alleninstitute.org](mailto:peterg@alleninstitute.org)>; PlatformDev <[platformdev@alleninstitute.org](mailto:platformdev@alleninstitute.org)>
Subject: RE: Failures in DF_OVER_F_COMPUTATION_V2_QUEUE
 
Hi, the docker image for ophys_etl has been updated with the latest changes [1]. Restarting the failed jobs should pull this updated image. 

1. [alleninstitutepika/ophys_etl_pipelines Tags | Docker Hub](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhub.docker.com%2Fr%2Falleninstitutepika%2Fophys_etl_pipelines%2Ftags&data=05%7C01%7C%7C507f13edc45642f2046308db2988b763%7C32669cd6737f4b398bddd6951120d3fc%7C0%7C0%7C638149439385323761%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=z2YyIO7cFZpctCLHdVZpMJGl9GVLF8gw7NL0Igj1IBQ%3D&reserved=0)

 
From: Zeb Haradon <[zebh@alleninstitute.org](mailto:zebh@alleninstitute.org)> 
Sent: Monday, March 20, 2023 12:19 PM
To: Mike Huang <[mike.huang@alleninstitute.org](mailto:mike.huang@alleninstitute.org)>; Chris Morrison <[chris.morrison@alleninstitute.org](mailto:chris.morrison@alleninstitute.org)>; Pika <[Pika@AllenInstitute.onmicrosoft.com](mailto:Pika@AllenInstitute.onmicrosoft.com)>
Cc: Jerome Lecoq <[jeromel@alleninstitute.org](mailto:jeromel@alleninstitute.org)>; Peter Groblewski <[peterg@alleninstitute.org](mailto:peterg@alleninstitute.org)>; PlatformDev <[platformdev@alleninstitute.org](mailto:platformdev@alleninstitute.org)>
Subject: RE: Failures in DF_OVER_F_COMPUTATION_V2_QUEUE
 
Thank you. I’m not sure how informatics changes get deployed. Do you know when this will be on production? I’ll need to restart the failed jobs after it is.
 
From: Mike Huang <[mike.huang@alleninstitute.org](mailto:mike.huang@alleninstitute.org)> 
Sent: Monday, March 20, 2023 12:12 PM
To: Chris Morrison <[chris.morrison@alleninstitute.org](mailto:chris.morrison@alleninstitute.org)>; Zeb Haradon <[zebh@alleninstitute.org](mailto:zebh@alleninstitute.org)>; Pika <[Pika@AllenInstitute.onmicrosoft.com](mailto:Pika@AllenInstitute.onmicrosoft.com)>
Cc: Jerome Lecoq <[jeromel@alleninstitute.org](mailto:jeromel@alleninstitute.org)>; Peter Groblewski <[peterg@alleninstitute.org](mailto:peterg@alleninstitute.org)>; PlatformDev <[platformdev@alleninstitute.org](mailto:platformdev@alleninstitute.org)>
Subject: RE: Failures in DF_OVER_F_COMPUTATION_V2_QUEUE
 
Hi Zeb,
 
I investigated the issue and merged in a fix. There were recent changes to the DFF calculation as requested by Jinho [1].
However, there was an edge case where a trace may be all-nan values if the ROI has been tagged with an exclusion-label. The code now deals with that case and it should behave similarly before my previous update in that regard.

Regards,
Mike

1. 
[Changing DFF calculation code · Issue #537 · AllenInstitute/ophys_etl_pipelines (github.com)](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAllenInstitute%2Fophys_etl_pipelines%2Fissues%2F537&data=05%7C01%7C%7C507f13edc45642f2046308db2988b763%7C32669cd6737f4b398bddd6951120d3fc%7C0%7C0%7C638149439385323761%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CaX03wV6c%2FEoIRc3T9EiXmGzsF6IUk4e2xExSwsfTf0%3D&reserved=0)
 
From: Chris Morrison <[chris.morrison@alleninstitute.org](mailto:chris.morrison@alleninstitute.org)> 
Sent: Friday, March 17, 2023 3:51 PM
To: Zeb Haradon <[zebh@alleninstitute.org](mailto:zebh@alleninstitute.org)>; Pika <[Pika@AllenInstitute.onmicrosoft.com](mailto:Pika@AllenInstitute.onmicrosoft.com)>
Cc: Jerome Lecoq <[jeromel@alleninstitute.org](mailto:jeromel@alleninstitute.org)>; Peter Groblewski <[peterg@alleninstitute.org](mailto:peterg@alleninstitute.org)>; PlatformDev <[platformdev@alleninstitute.org](mailto:platformdev@alleninstitute.org)>
Subject: Re: Failures in DF_OVER_F_COMPUTATION_V2_QUEUE
 
Hey Zeb,
 
Thanks for the heads up. We’re looking into the issue.
 
Chris
 
From: Zeb Haradon <[zebh@alleninstitute.org](mailto:zebh@alleninstitute.org)>
Date: Friday, March 17, 2023 at 3:33 PM
To: Pika <[Pika@AllenInstitute.onmicrosoft.com](mailto:Pika@AllenInstitute.onmicrosoft.com)>
Cc: Jerome Lecoq <[jeromel@alleninstitute.org](mailto:jeromel@alleninstitute.org)>, Peter Groblewski <[peterg@alleninstitute.org](mailto:peterg@alleninstitute.org)>, PlatformDev <[platformdev@alleninstitute.org](mailto:platformdev@alleninstitute.org)>
Subject: Failures in DF_OVER_F_COMPUTATION_V2_QUEUE

Pika,
 
We're having an issue where the DF_OVER_F_COMPUTATION_V2_QUEUE is failing. The error message is "ValueError: array of sample points is empty", and most have a few warnings as well, "All-NaN slice encountered r, k = function_base._ureduce(a, func=_nanmedian, axis=axis, out=out". We haven't changed anything relevant in lims processing, and the strategy file has not changed in a year. The failures just started recently and are impacting LearningmFISHTask1A and OpenScopeDendriteCoupling. As far as we can tell, there are no differences in the data.
 
Here is the issue: AI_requests0088764
Here is an example log from a failure: http://lims2/job_logs?id=1254329581
 
Does anyone have any insight into what might be happening here?
 
Thanks

**Comment by Ahad-Allen** [comment]
Looked over the LIMS2 jobs queues and these sessions seem to be passing this step now! I think we can convert them now :)
