### ISSUE TITLE
Add Plane Number to Ophys NWB

### ISSUE THREAD

**Issue by Ahad-Allen** [AllenInstitute/OpenScopeNWB#109]

**Comment by jeromelecoq** [comment]
We need to find where the image plane group is set in the SDK. 
Some data will need to be pulled to replace placeholder.

**Comment by jeromelecoq** [comment]
Ahad is in the middle of investigation. We need to check the original query for data consistency and follow the data from there.

**Comment by Ahad-Allen** [comment]
The query and data consistency seem to be alright here, the actual problem is seems to be that the option to write that metadata into the nwb is False by default. I am running some tests with it set to true and will analyze the files when they are generated.
