### ISSUE TITLE
Establish a reliable, robust way to re-trigger conversion and upload of  all previously uploaded files.

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#110]

**Comment by jeromelecoq** [comment]
@Ahad-Allen need to make a PR to push the code and explain how it works.

**Comment by Ahad-Allen** [comment]
Tracked with #118. We are able to run a script which changes the status of all uploading scripts to converting. This means that 

1. Future runs of the cron will see those session are converting and not restart the conversion
2. Only finished sessions will be regenerated
3. In the event of a failure, the sessions which are marked as still being converted will be safe to manually retrigger
