### ISSUE TITLE
Include stim info in LFP files?

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/OpenScopeNWB#112]
I have made two notebooks now that rely on aligning LFP data to stimulus times. It's not a big problem to do this with our current situation; It just requires downloading and opening two NWB files from the same session at the same time. But if possible, wouldn't it be better to include stim info within the LFP files?

**Comment by rcpeene** [comment]
Same goes for regular Ophys files. Would be useful for my notebooks.

**Comment by jeromelecoq** [comment]
Let's just refer people to the notebook that explain this already
