### ISSUE TITLE
Some Deep Planes Have issues with segmentation

### ISSUE THREAD

**Issue by Ahad-Allen** [AllenInstitute/OpenScopeNWB#113]
![Image](https://user-images.githubusercontent.com/87045911/230177462-8ff3b58e-23a7-4f90-9b86-cd094edf24d6.png)

**Comment by Ahad-Allen** [comment]
Tracked with https://github.com/AllenInstitute/AllenSDK/issues/2683

**Comment by Ahad-Allen** [comment]
Currently testing the patch released by the sdk team

**Comment by Ahad-Allen** [comment]
Sam released  a patch that I am trying now. Originally the problem with the older version of the branch was that the ophys timestamps were not being used after being pulled and were instead being pulled from the dff file.

**Comment by Ahad-Allen** [comment]
The patch worked and I was able to succesfully add raw data to the files and upload them to dandi! The files are located at https://dandiarchive.org/dandiset/000336/draft/files?location=sub-641331

**Comment by jeromelecoq** [comment]
Lots of planes were uploaded
Carter to make summary table using the notebook and send this to the team for validation.

**Comment by jeromelecoq** [comment]
The problem was related to dff being empty. We will use the metadata table from Carter to confirm that all experiment were uploaded

**Comment by jeromelecoq** [comment]
This was fixed, @Ahad-Allen will make a PR to contain the final uploading code.
