### ISSUE TITLE
Follow up on imread issue for cell matching with Tech team

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#115]

**Comment by Ahad-Allen** [comment]
We need to follow-up on https://github.com/AllenInstitute/AllenSDK/issues/2672 to make sure that our SDK changes align with what the SDK's main code is doing. The code change will allow for the projection images of ophys files to be represented as 0-255 ints correctly.

**Comment by Ahad-Allen** [comment]
I've scheduled a meeting with Adam on Wednesday to discuss how to handle the SDK issues and making PRs for all these unrelated tickets :)

**Comment by Ahad-Allen** [comment]
Tracked with https://github.com/AllenInstitute/AllenSDK/pull/2682

**Comment by Ahad-Allen** [comment]
The AllenSDK team asked me to add a Unit test for the reading of the projection images and the verification that they are now 0-255.

**Comment by Ahad-Allen** [comment]
This has been merged!
