### ISSUE TITLE
Add denoised movie to dendritic coupling nwb file.

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#117]
The goal of this is to add denoised movie after DeepInterpolation into NWB files on Dandi. Probably a separate file given the size. We would run a nextflow workflow either on code ocean or the cluster and append the data to the NWB and reupload to Dandi.

**Comment by jeromelecoq** [comment]
We are currently waiting for a meeting to be scheduled with Tim, Joel, Ahad, Jay

**Comment by jeromelecoq** [comment]
Ahad is uploading to dandi, files were created

**Comment by Ahad-Allen** [comment]
Movie is up at https://dandiarchive.org/dandiset/000336/draft/files?location=sub-621602

**Comment by Ahad-Allen** [comment]
The other 2 test files are generated, I am manually uploading them now.

**Comment by Ahad-Allen** [comment]
They are uploaded and the team will be reviewing them

**Comment by jeromelecoq** [comment]
Files were good. We now need to scale up with another ticket
