### ISSUE TITLE
Fix tif stack from one mouse

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#122]

**Comment by Ahad-Allen** [comment]
The file at /allen/programs/mindscope/workgroups/openscope/aws_buckets_auto_upload/2022-dendritic-coupling/20230412_661749_Visam_Vispm_corticalstack_retake_00001.tif has a corrupted frame on page 27835. I am able to split the file into roi files properly and skip the corrupted frame. I am working on updating the generated files so that the location of the skipped frame is not stored in the newly generated file.

**Comment by jeromelecoq** [comment]
Ahad will try to test the stack fixing code by generating a short stack and load in Fiji

**Comment by Ahad-Allen** [comment]
I created a short stack and had the same issue, but after some thought I think this is an artifact of the splitting part of the code designed to separate the brain areas. i am trying the same functionality without this to see what the result is .

**Comment by Ahad-Allen** [comment]
Per Jerome's request, I am attaching the code used for the offset stack updating:
`def merge_tiff_files(tif_data, output_path):
    """ Concats a list of tiff files into a single tiff file

    Parameters
    ----------
    tif_data : list
        List of coordinates from a tiff file
    output_path : str
        Path to output file
    
    Returns
    -------
    """
    
    with tifffile.TiffWriter(output_path, bigtiff = True, append=True) as tif:
    
        # Save the image data as a new page in the TIFF file
        tif.save(tif_data)
    #tifffile.imsave(output_path, tif_data, append=True)

def update_offsets_and_byte_counts(tiff_file, removed_frame_index):
    tiff = tifffile.TiffFile(tiff_file)

    header = 2384
    num_pages = len(tiff.pages)

    if removed_frame_index >= num_pages - 1:
        return

    for i in range(removed_frame_index + 1, num_pages):
        page = tiff.pages[i]

        # Update StripOffsets
        strip_offsets = page.tags["StripOffsets"].value
        for j in range(len(strip_offsets)):
            strip_offsets[j] -= (2543616 + header)
        page.tags["StripOffsets"].value = strip_offsets

       
    # Save the updated TIFF file
    tiff.save('merged0.tif')
    tiff.close()`

**Comment by jeromelecoq** [comment]
Ahad checked the backup and found the files worked. 

@Ahad-Allen will copy to AWS folder with proper renaming and notice the team when that is done.

**Comment by Ahad-Allen** [comment]
Shiella placed the file in: /allen/programs/mindscope/workgroups/openscope/aws_buckets_auto_upload/2022-dendritic-coupling/230531_reupload661749_. Should be reuploaded now!

**Comment by jeromelecoq** [comment]
We suspect there is a copy paste pb as this happened again

**Comment by Ahad-Allen** [comment]
The file worked for the team!
