### ISSUE TITLE
Illusion files have issues with matnwb

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#123]

**Comment by jeromelecoq** [comment]
ping vijay

**Comment by jeromelecoq** [comment]
Sent a follow up email: 

Hi Vijay,
 
I hope all is good. 
I am following on this thread. Should we file a bug related to this? We have this ticket on our board and we just are curious what is the best way to move forward.

Thanks!
Jerome Lecoq
 
From: Vijay Iyer <[vijayi@mathworks.com](mailto:vijayi@mathworks.com)>
Date: Thursday, May 18, 2023 at 3:03 PM
To: Jerome Lecoq <[jeromel@alleninstitute.org](mailto:jeromel@alleninstitute.org)>, Ahad Bawany <[ahad.bawany@alleninstitute.org](mailto:ahad.bawany@alleninstitute.org)>
Cc: Carter Peene <[carter.peene@alleninstitute.org](mailto:carter.peene@alleninstitute.org)>
Subject: RE: MatNWB

CAUTION: This email originated from outside the Allen Institute. Please do not click links or open attachments unless you've validated the sender and know the content is safe.
Sounds good. I’ve updated the [project description](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1yMJEIgfr8za-x_X4iWoz7hAInbq-bfQAvaYlWrKMsvU%2Fedit%23heading%3Dh.niur16kklk5h&data=05%7C01%7C%7C1a7a29dd76a94389196608db57ebb971%7C32669cd6737f4b398bddd6951120d3fc%7C0%7C0%7C638200442212633054%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=d5vSeCmrivrD7JIfMP7VJfyk7BtmflIAU0bvSmmUkhc%3D&reserved=0) to reference the OpenScope dataset as a core goal.

Let’s see if we get an interested candidate. If so, we should promptly open up the permissions discussion.
 
Vijay

**Comment by jeromelecoq** [comment]
@Ahad-Allen to submit issue to repository

**Comment by Ahad-Allen** [comment]
Issue submitted!
