### ISSUE TITLE
Determine Methodology for Working with and Maintaining Capsules

### ISSUE THREAD

**Issue by Ahad-Allen** [AllenInstitute/OpenScopeNWB#126]
We would like to reach out to David Feng to get advice on how to maintain Capsules and best practices for working with code bases with them. I will create a group chat on teams to help facilitate this.

**Comment by Ahad-Allen** [comment]
The team at AIND directed me to a living document on this which seems to be quite early but helpful: https://alleninstitute.sharepoint.com/:w:/s/NeuralDynamics/EVWKomcUXANDnGSzAqTB5XcBuSzQlhQ0FXXvsyxi9Tzh1g?e=3DweGr&isSPOFile=1

**Comment by Ahad-Allen** [comment]
AIND has indicated that the current best practice is using one repo per capsule and following a specific template for each capsule is ideal. We will follow this and will keep this issue open to update as we develop our process.

**Comment by jeromelecoq** [comment]
@Ahad-Allen to monitor until the methodology is stabilized. Perhaps once it is stable, we could discuss it.

**Comment by jeromelecoq** [comment]
Let's close this. This is managed by another group
