### ISSUE TITLE
One mouse has new experimental stimuli issue in OpenScopeDendriticCoupling

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#127]
@Ahad-Allen to add metadata with issue

**Comment by Ahad-Allen** [comment]
sub-631188_ses-1212228954 was presented: {'drifting_gratings_contrast_presentations', 'drifting_gratings_TF_presentations', 'spontaneous_presentations']. Sent info to sheilla
