### ISSUE TITLE
Add Barcoding to firebase.

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/OpenScopeNWB#130]
Barcoding needs to be added to firebase to facilitate the conversion of the pilot project. I will run my add project scripts for this now.

**Comment by Ahad-Allen** [comment]
Done 

![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/87045911/06f6073d-5f1d-4d6a-8f27-6b0b5187dd79)
