### ISSUE TITLE
Add dendritic/somatic metadata string to NWB files

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#131]
the goal is to provide information on which planes were targeted for dendritic recordings and which plane for somatic recording in the Dendritic Coupling experimental design. 

One way to implement this is to add a key/tag to NWB files with a description of what the key means.

**Comment by jeromelecoq** [comment]
Add a string to the files.

**Comment by jeromelecoq** [comment]
Let's do this on the dataportal 

We currently have ("Plane number", "experimentID") for each plane. 
We want ("Plane number", "experimentID", "depth_in_um", "Layer I/Layer 2/3/Layer 5")

**Comment by Ahad-Allen** [comment]
I finished the code to add this to the portal. The query was pretty simple for each depth:
`    Ophys_DEPTH_QRY = '''
    SELECT de.depth
    FROM ophys_experiments oe
        JOIN ophys_sessions os ON os.id = oe.ophys_session_id
        LEFT JOIN imaging_depths de ON de.id = oe.imaging_depth_id
    WHERE oe.id = {}`

 going to test it now!
