### ISSUE TITLE
Many sessions that had one or more failed plane were not uploaded. Need pipeline fix and PR

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#133]
Let's finish the excel sheet and make a list of missing planes using it.

**Comment by Ahad-Allen** [comment]
https://docs.google.com/spreadsheets/d/1TCbagOJEyQDl9-2M6eduYAkRVZ_M2CCSEbUYFSAqpJU/edit#gid=0 Is what we have. This is mouse level and doesn't have planes currently. Should we share with the team and then add planes, or add the planes first?

**Comment by jeromelecoq** [comment]
All planes wre uploaded
