### ISSUE TITLE
Update script that update the firebase content based on internal database (POSTGRESQL) to ALSO update based on external database (DANDI).

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#134]
This is to make sure the database is synced with DANDI. Essentially add a second loop to realign the database with Dandi.

**Comment by jeromelecoq** [comment]
Did you make a PR for this? Can you add it here?

**Comment by Ahad-Allen** [comment]
https://github.com/AllenInstitute/OpenScopeNWB/pull/157
