### ISSUE TITLE
Ahad to check for 655042 zstack

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#135]
This mouse was acquired as part of omfish directly. No z-stack?

**Comment by Ahad-Allen** [comment]
This mouse was originally part of omfish but was used for openscope. It failed brain health checks. Not sure if we should keep the data in that case? We can discuss during the standup.

**Comment by jeromelecoq** [comment]
The data should not have been uploaded. It failed for brain health
