### ISSUE TITLE
Investigate why some mice for dendrite coupling have so many planes where non-ophys nwb files are generated

### ISSUE THREAD

**Issue by Ahad-Allen** [AllenInstitute/OpenScopeNWB#139]
Some mice (e.g. 4972 and 1603) have an unusually high number of sessions where most of their experiments don't have dff files and trigger the alternative conversion of files which are marked as not having "ophys" data in their name. Unsure why and this needs to be investigated.

**Comment by jeromelecoq** [comment]
@Ahad-Allen to copy error stack on failing jobs. 
It seems that all L5 cells have that issue.

**Comment by Ahad-Allen** [comment]
Something weird is going on, the jobs aren't marked as fails for the L5 mice, but rather seem to have never even started: Here's a comparison of  experiment 1245934428  and experiment 1243680865.



![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/87045911/c2b67c14-61b3-41d8-892e-719f48e05b5e)



![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/87045911/72a09c74-f4c3-4cfd-addd-4dca67d78ccc)


Note how the first experiment only has 3 jobs associated with it, which are all marked as successes! I have some more info I will attach in another message in a moment about the details from the jobs.

**Comment by Ahad-Allen** [comment]
![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/87045911/c5af80b1-3315-4c37-a157-318b25c5ce3d)

Seems like we just need to get the other sessions with the first issue triggered and we should be good to go!

**Comment by Ahad-Allen** [comment]
I asked chris to trigger the other sessions and am just waiting on them.

**Comment by Ahad-Allen** [comment]
Chris has triggered the sessions! They are converting now :)
