### ISSUE TITLE
Add n_repeats information to the BarCoding Stimulus

### ISSUE THREAD

**Issue by Ahad-Allen** [AllenInstitute/OpenScopeNWB#143]
There is an nrepeats value associated with the stimulus of this project in its pickle file. Pamela would like to have this packaged into the nwb files in order to align her data relevant to the repeat number. I am not sure why this part of the pickle file was not packaged by the stimulus module, so I will investigate and then update the issue with how to move forward.

**Comment by Ahad-Allen** [comment]
I have identified the problem here. The code that is used to create the stim table is present here:  https://github.com/AllenInstitute/AllenSDK/blob/master/allensdk/brain_observatory/ecephys/stimulus_table/ephys_pre_spikes.py#L263. This code looks at the stim, stim_path, sweep_frame,  sweep_order, display_sequence, dimnames, and sweep_table keys of the 'stimuli' key of the pickle file to generate columns for the stim table in our nwb files. The code here attempts to find unique and repeated keys within the 'stim' key to add to the table if needed.

The problem with including our 'runs' key is that is a unique key within stimuli, rather than being a key within the 'stim' key of the stimuli. Because of this, the code never looks at this part of the pickle and does not package it.

**Comment by Ahad-Allen** [comment]
I investigated this a bit more with jerome's help yesterday. It seems like our pkl files store the number of repeats, but not the CURRENT repeat that a stim is on. It could be possible to add this information into the nwb files without changing the pickle files, but I am not sure of the best approach to doing so.

**Comment by jeromelecoq** [comment]
@Ahad-Allen to look into how to add column to the stim_table.

**Comment by Ahad-Allen** [comment]
We decided the best approach to handling this is adding the info to the csv. We are contacting Pamela to get an exact sense of how we want to represent this in the stim table.

**Comment by Ahad-Allen** [comment]
Jerome is going to use 
stimulus_obj = Stimulus(visual.GratingStim(window,
                        pos=(0, 0),
                        units=‘deg’,
                        size=(250, 250),
                        mask=“None”,
                        texRes=256,
                        sf=0,
                        ),
        # a dictionary that specifies the parameter values
        # that will be swept or varied over time during the presentation of the stimulus
        sweep_params={
                    # works similarly like for loops
                    # for a fixed contrast value, Contrast is updated every video frame
                ‘Index’ : (np.arange(n_repeats), 0),
                ‘Contrast’: ([1], 1),
                ‘Color’:(list_of_contrasts, 2)
                },
        sweep_length=1.0/frame_rate,
        start_time=0.0,
        blank_length=0,
        blank_sweeps=0,
        runs = 1,
        shuffle=False,
        save_sweep_table=True,
        )
to add an 'index' that is the current run number to each frame in camstim

**Comment by jeromelecoq** [comment]
As soon as we get one exp, we should test NWB conversion

**Comment by Ahad-Allen** [comment]
Files for 2 mice are going up soon, we can test conversions with this method :)

**Comment by Ahad-Allen** [comment]
Files are up at https://dandiarchive.org/dandiset/000563/draft/files?location=sub-682745

**Comment by jeromelecoq** [comment]
Files have the right columns, including the repeat column. Closing
