### ISSUE TITLE
Delete irrelevant sessions from the dendrite coupling dandi

### ISSUE THREAD

**Issue by Ahad-Allen** [AllenInstitute/OpenScopeNWB#146]
We need to delete some extra sessions from the dendrite dandi. Jerome suggested that we create a list here and then share it on slack for the team to give feedback on before deleting.

Here are the sessions I think should be deleted for sure:
ALL SESSIONS from mice: 634402, 641331,638955, 641998, 655042, 657962. These mice are all fails or shown the wrong stim
All sessions from 647715. This is the mouse that was shown the v15 and had the brain compression issue.

Should the sessions which were later retaken be deleted? For example, if U3 was retaken, should the original be deleted?

**Comment by Ahad-Allen** [comment]
The team asked me to start by deleting 638955 and this is done! They are using the other failed mice for some hab analysis.

**Comment by jeromelecoq** [comment]
The team asked to delete pre-ophys sessions.

**Comment by Ahad-Allen** [comment]
Done! :)
