### ISSUE TITLE
Add raw movies to Code Ocean packaging capsule

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/OpenScopeNWB#158]
Jerome's files that include the 2p movie have the following key; `motion_corrected_movie`. We agree this is a better key than the current one for our files. We should change it.

**Comment by jeromelecoq** [comment]
Let's look into documenting the key into the nwb file? 
Maybe @Ahad-Allen list here the requirement from NWB standard for this.

**Comment by Ahad-Allen** [comment]
There are actually no specifications for the naming convention in the schema for 2photonseries, BUT there is a useful "comments" key which might be important for us adding information on the processing details for these movies:


![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/87045911/3f9f9799-1a61-4113-a6bd-34820ecaf010)

**Comment by jeromelecoq** [comment]
Let's do this for the July release.

**Comment by jeromelecoq** [comment]
Let's fix this on Code Ocean

**Comment by jeromelecoq** [comment]
We will need to add raw movies to the packaging capsule.

**Comment by jeromelecoq** [comment]
Tracked here https://github.com/orgs/AllenNeuralDynamics/projects/75/views/1?filterQuery=raw&pane=issue&itemId=71821158
