### ISSUE TITLE
Illusion project were reuploaded but some path and missing NWB are present

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#159]
1. Mice id between new files with onto-gen and template does not match old files
2. There is one extra mouse of data missing?

**Comment by Ahad-Allen** [comment]
1. The mouse id problem is the one we noted with dendrite coupling with the difference between donor_name and donor_id causing 10 digit numbers which are incorrect to appear. I think the best approach here is to just change to the 6 digit donor id for consistency.
2. This is session 1184671550. Will look into why this session has a problem :)

**Comment by jeromelecoq** [comment]
Ahad will regenerate with the 6 digits mouse id, and reupload. Will need to update the ephys code as well.

**Comment by Ahad-Allen** [comment]
The 6 digit ids are generated and uploaded!
