### ISSUE TITLE
LFP times have issues with online alignment causing strange Delta Values for barcoding

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#160]

**Comment by jeromelecoq** [comment]
They changed the type of alignment in openEphys to an online alignement
The curent rig is incompatible with this new process. 

In order to fix, we need to generate a new file lip-samples.npy from sample-numbers.py.
The new file will stored in a temp directory during processing and submitted with the input-json file.

We can delete it after processing.

**Comment by jeromelecoq** [comment]
@Ahad-Allen need to ask Ben to upload sample-number.npy

**Comment by jeromelecoq** [comment]
File is already there per Ben response

**Comment by jeromelecoq** [comment]
@Ahad-Allen to add info on latest test run

**Comment by Ahad-Allen** [comment]
I had an issue with finding the correct file path, but that is resolved. I am running it again. I am generating the timestamps for the LFP, with a stride of 12, like so:
`    lfp_samples_path= glob(join(module_params['base_directory'],
                                    "**/*",
                                    probe_idx +
                                    '*sample_numbers.npy'))[0]
    lfp_samples=np.load(lfp_samples_path)
    lfp_samples=lfp_samples-np.min(lfp_samples)
    lfp_samples=lfp_samples*12
    output_path = join(module_params['output_path'], probe_idx + '_lfp_timestamps.npy')
    np.save(output_path, lfp_samples)`

**Comment by Ahad-Allen** [comment]
This method worked for generating files for 1274061513! 1275082330 seems to be missing the sample numbers files for probes A B and C, I've contacted Ben to see if they can be uploaded :)
