### ISSUE TITLE
Convert sessions for failed mice for Dendrite

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#167]

**Comment by jeromelecoq** [comment]
Ahad is using jay sheet to check mice uploaded. It goes through all sessions.

**Comment by Ahad-Allen** [comment]
Triggered the sessions that are non-raw, will do the raw ones next.

**Comment by Ahad-Allen** [comment]
Going to run validation to verify all are up but these should all be done other than the ophys files which need to be renamed. I will handle that either later today or early tomorrow

**Comment by Ahad-Allen** [comment]
Asking the dendrite team to confirm this looks good, but everything should be converted now :)

**Comment by Ahad-Allen** [comment]
The team is happy with their data! Looks like we have all the raw and non-raw up
