### ISSUE TITLE
Update alignment tool to dynamically handle failed probes

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#168]
Ahad to meet with Severine to fix notebook that does alignment before CCF registration. It should work when one probe is broken.

**Comment by Ahad-Allen** [comment]
Code ocean port should work! going to meet with Sev about this during the afternoon today :)

**Comment by jeromelecoq** [comment]
We will discuss at the NWB alignment meeting>

**Comment by Ahad-Allen** [comment]
We will likely want to do something using AWS like Matt Davis's team for creating online tools, or creating a webapp like Arielle's team. Will need to continue communicating with the team and see what approach works best. In the mean time I have sent the code to Sev and she should be good to continue for now

**Comment by Ahad-Allen** [comment]
I sent ryan and Sev this for feedback, they are going to look at it today.
