### ISSUE TITLE
Some experiment from BarCoding have sync issues. Mouse number 692360. Need to investigate to fix

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#174]

**Comment by Ahad-Allen** [comment]
The mouse seems to have some issues with 0.5 second 'flickers' in the sync file. It is currently in the refinement stage and does not have files on LIMS, so i can not run tests to verify yet. I have messaged Sev about the mouse to see when we can try packaging it.

**Comment by Ahad-Allen** [comment]
Using the allenSDK's get_edges function to get photodiode timestamps, I found that the 0 time sync jumps are filtered out as are MOST of the 0.5 second ones. There are exactly 2 timestamps which do not get filtered out. I think we could add a check for delta Ts of around 0.5 and remove them from the file. We can then just point to that file as the sync data for this session manually.

**Comment by Ahad-Allen** [comment]
There are 2 other mice affected by this, which seem to be affected more heavily. 692986 AND 695435. These two have hundreds of the 0.5 second pulses, rather than just 2. Here is an example of the level of jumps: 

![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/87045911/d7f2d9cd-41a7-4e3b-8eea-205089860b98)

Ben, Jerome, and I are in a teams chat to diagnose the issue.

**Comment by jeromelecoq** [comment]
Ahad to schedule quick meeting with people that understand part of the issues.

**Comment by Ahad-Allen** [comment]
I will create some quick notebooks to go over each mouse before we meet tomorrow

**Comment by Ahad-Allen** [comment]
We found that the 695435 mouse had 7 extra frames for its vsyncs. Each of these was extremely small, so we decided to filter them out for running speed. We found that the SDK already uses something like when calculating the times for stimuli, so the extra frames are not a concern there.

![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/87045911/330be4be-5589-4af9-977b-96e9217239e9)

**Comment by jeromelecoq** [comment]
Carter to check that the file is good with physic

**Comment by jeromelecoq** [comment]
Receptive field looks good. 
Carter to copy it here.

**Comment by rcpeene** [comment]
I tested the receptive field notebook on this file. Selected units on ProbeB that have isi_violation < 1, firing rate > 0.1, and "good" quality. Here they are. It may be worth noting that I consider a spike as a 'response' to the visual stimulus if it occurs within 0.2 seconds of the stim.



![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/23059582/a6bd7d6d-b281-4e09-bd67-5a841d5f8055)

**Comment by jeromelecoq** [comment]
Add a note to data portal on this exp
"Low receptive yield on probe B, Some units have receptive fields. Timing issue was fixed in post-processing."

**Comment by Ahad-Allen** [comment]
Added note
