### ISSUE TITLE
stim table with time series does not translate to CSV well

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/OpenScopeNWB#175]
I'm attempting to do a quick search on the stim table for GLO. To do this, I'd like to save it as a csv using the line 
```
stim_table.to_dataframe().to_csv("temp.csv")
```
This produces a CSV but I think, because there is a column containing a time series, the resulting CSV looks a bit obstructed.

Table with timeseries:
![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/23059582/b665e93b-2ff1-44f2-9e18-8035f8e23ade)

Outputted CSV:
![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/23059582/d545fa74-e5e6-44d0-b69b-b5df47d388ff)

I'm unsure if there's anything to be done about this or if it really constitutes a problem, but I figured it was worth consideration.

**Comment by jeromelecoq** [comment]
We made a full notebook to explain the stimulus. Let's close
