### ISSUE TITLE
Add STIM templates to ophys files

### ISSUE THREAD

**Issue by Ahad-Allen** [AllenInstitute/OpenScopeNWB#176]
Currently, the dendrite NWB files are missing their stimulus movies. We need to attach them to each file, which will increase the file size by ~4 gigs.

**Comment by Ahad-Allen** [comment]
I went through the documentation for pynwb and it looks like we can use an image series to store these movies, very similarly to what we do for the ecephys templates. Will try an example generation today

**Comment by jeromelecoq** [comment]
Some code is working. Ahad will make a code ocean capsule to append template

**Comment by Ahad-Allen** [comment]
Repo here: https://codeocean.allenneuraldynamics.org/capsule/0862591/tree

**Comment by Ahad-Allen** [comment]
sub-621602/sub-621602_ses-1194555869-acq-1194754131_image+ophys.nwb has a denoised file with templates for carter to use :)

**Comment by Ahad-Allen** [comment]
https://github.com/AllenInstitute/DendriteTemplateCapsue
