### ISSUE TITLE
Illusion has template order issues in its NWB files.

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#177]
The template images were in the wrong order. 
Ahad is fixing this with new uploads

**Comment by Ahad-Allen** [comment]
Files look to be up! Will confirm with Hyeyoung.

**Comment by jeromelecoq** [comment]
Currently the filename is used as key for the image series in the NWB. Here is an example: 

![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/2491343/b39042ee-1c8a-4fe8-9156-ca5a9064aeb6)

**Comment by jeromelecoq** [comment]
This is fixed
