### ISSUE TITLE
Ask MPE and Ben about the suspiciously high running deltas

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/OpenScopeNWB#178]
I did a survey of many Illusion, GLO, and Barcoding files and found that they have a lot of variation in their running timestamp diffs.

**Comment by rcpeene** [comment]
**BARCODING** 
sub-688546_ses-1295360519
![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/23059582/7b92d76b-488d-4c04-8baa-2a48d5eb93f0)

sub-691524/sub-691524_ses-1298257492.nwb
![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/23059582/6962f9c3-1e2a-4cf7-9966-93b4eda2310a)

sub-681446/sub-681446_ses-1298465622_ogen.nwb
![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/23059582/f0a1783f-801c-43a9-8ac2-fca14801405a)

sub-682745/sub-682745_ses-1290822286_ogen.nwb
![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/23059582/5a82ae94-82dd-47a3-8efa-694bc197fe87)

sub-685263/sub-685263_ses-1292234897_ogen.nwb
![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/23059582/c230c627-7a9e-40a3-a1fb-1ce57ff27e06)


**ILLUSION**
sub_1174569641/sub_1174569641sess_1184671550/sub_1174569641+sess_1184671550_ecephys.nwb
![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/23059582/e3559865-de96-4d32-99a0-d7b48441a52f)

![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/23059582/1304531b-952a-47c1-8bea-3a17ce94b5e2)
sub_1172969394/sub_1172969394sess_1183070926/sub_1172969394+sess_1183070926_ecephys.nwb

![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/23059582/ecb2b844-c123-4efc-8a92-dc7f3a4a8bf8)
sub_1176214862/sub_1176214862sess_1188137866/sub_1176214862+sess_1188137866_ecephys.nwb

![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/23059582/123e55a6-1f94-4ac5-837c-18f0fd0746ab)
sub_1171903433/sub_1171903433sess_1181330601/sub_1171903433+sess_1181330601_ecephys.nwb


**GLO**
sub-1169714184/sub-1169714184.nwb
![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/23059582/18ce2ecb-60a0-4e74-a93b-d0375cb983b7)

sub-1169714184/sub-1169714184.nwb
![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/23059582/0b250890-eb98-42aa-a633-de2d6e1e00d7)

sub-1170220944/sub-1170220944.nwb
![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/23059582/6cbe24fc-1fbb-4707-b80a-dcc26e3e9e85)

**Comment by jeromelecoq** [comment]
Jerome will reach out to MPE

**Comment by bjhardcastle** [comment]
I think the vsyncs should be used directly as wheel encoder sample times - is that what's happening?

The thick line on the line plot might be making this look worse than it really is.. 

Here are histograms for two of the worst sessions above: 

`sub-688546_ses-1295360519`:
![688546_20230907_vsync_interval_histogram](https://github.com/AllenInstitute/OpenScopeNWB/assets/63425812/433446f8-7f0e-4844-b9e8-7804104108b0)

`sub-681446/sub-681446_ses-1298465622_ogen.nwb`
![692072_20230921_vsync_interval_histogram](https://github.com/AllenInstitute/OpenScopeNWB/assets/63425812/be11de4b-5e1e-4fa9-ab50-6f64aaedb018)

**Comment by jeromelecoq** [comment]
Could plot this on a y-log scale, that might allow us to count how many times we steer off?

**Comment by jeromelecoq** [comment]
Carter to make a quick plot on the worst bar code to confirm those are rare events.

**Comment by jeromelecoq** [comment]
when we package our NWB files, we have a step that is cleaning up spurious wheel data
here is a copy of the relevant lines of code

```
df = pd.DataFrame(
        {
            "start_time": start_times,
            "end_time": end_times,
            "velocity": linear_velocity,
            "net_rotation": dx_rad,
        }
    )
    # due to an acquisition bug (the buffer of raw orientations may be updated
    # more slowly than it is read, leading to a 0 value for the change in
    # orientation over an interval) there may be exact zeros in the velocity.
    df = df[~(np.isclose(df["net_rotation"], 0.0))]
```

As you can see this code will REMOVE timestamps that show abnormal wheel values

This is why when you plot the histogram of period, you get a plot like this :

![MicrosoftTeams-image1](https://github.com/AllenInstitute/OpenScopeNWB/assets/2491343/2a5988b9-2d6e-4368-8d29-d02d9b9731ea)

to confirm, when we REMOVE the line “df = df[~(np.isclose(df[“net_rotation”], 0.0))]” from our packaging code, we get this:


![MicrosoftTeams-image](https://github.com/AllenInstitute/OpenScopeNWB/assets/2491343/529ad7c3-7014-4b70-b175-c30ff5a42eae)

So all of those timestamps are due to wheel artifact removal code

**Comment by bjhardcastle** [comment]
Great!

Hopefully this also explains the issue with `1309235849` from earlier this week, where there was a mismatch between number of rotation samples and vsyncs.
