### ISSUE TITLE
Illusion NWB files are missing a frame column in stim table

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#181]
Generated NWB files on Dandi recently lost a frame column

**Comment by jeromelecoq** [comment]
Ahad to investigate what is causing this column to disappear.

**Comment by Ahad-Allen** [comment]
The problem is NOT that the column was removed. There was a minor change to the SDK which caused the "Image" column to not be renamed to "frame". this is because it was expecting Image to start with a lowercase i. I have resolved this and can regen.

**Comment by jeromelecoq** [comment]
This is fixed and uploading. 
@rcpeene should check
