### ISSUE TITLE
Pamela's files have their start times AFTER their stop times for spontaenous blocks in the stim

### ISSUE THREAD

**Issue by Ahad-Allen** [AllenInstitute/OpenScopeNWB#182]

**Comment by jeromelecoq** [comment]
@Ahad-Allen will add a write up here.

**Comment by Ahad-Allen** [comment]
Essentially, the spontanenous blocks point to the current timestamp of the block and then the 0th timestamp, rather than the next time stamp. So for the first spontaneous block at index 144400, it will point to a start time of index 144400 and an end time of index 0, rather than 144001. This is ocurring during the apply_frame_times function of the ecephys_pre_spikes module, but I am not sure of whether this is due to input data or an error with the function.  I have messaged Pamela about this in her thread on the issue to determine the priority of fixing this.

**Comment by Ahad-Allen** [comment]
Resolved! the issue was cuased by there being no time in between some blocks
