### ISSUE TITLE
Deprecated files/Messy dandisets

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/OpenScopeNWB#184]
In several of our dandisets, there are deprecated, misorganized, and misnamed files. I will attempt to summarize the various examples here. I believe @Ahad-Allen will go through and delete and reupload files accordingly.

**Comment by rcpeene** [comment]
**GLO**
* all subjects are using 10 digit subject IDs
* most subjects are using probe A, B, C... rather than 0, 1, 2...
* some subjects contain only one file, no probes. 
  * `sub-1170220944`, `sub-1186895111`, `sub-1196154898`, `sub-1197684740`, `sub-1210326246`, `sub-1214890312`, `sub-1218586772`, `sub-1223016396`, `sub-1223032972`
* contains nested directory for session:
  * `sub_1169714193`, `sub_1170220951`, `sub_1170425953`, `sub_1186895119`, `sub_1186895128`, `sub_1196154905`, `sub_1196167186`, `sub_1196664789`, `sub_1197684876`, `sub_1199273437`, `sub_1202441642`, `sub_1210326253`, `sub_1214404694`, `sub_1214890319`, `sub_1218586779`, `sub_1223032979`:
  * A whole bunch of these also include twice as many files as they should, half of which have a typo 's'
* contains two main files, one with `ecephys` and one without
  * `sub-1196664448`
* contains two sessions? 
  * `sub_1170425953` , `sub_1223016403`
* `sub-1170425945`: missing three probe files?

**Comment by rcpeene** [comment]
**Illusion**

* about a third of subjects are using 10 digit subject IDs
* most subjects ae using probe A, B, C... rather than 0, 1, 2...
* most files still using `+` to delimit sessions from subjects
* some files contain `sess` rather than `ses`
 * `sub_1171903433`, `sub_1172968426`, `sub_1172969394`, `sub_1174569641`, `sub_1175512783`, `sub_1176214862`, `sub_1177693342`, `sub_1181314060`, `sub_1181585608`, `sub_1182593231`, `sub_1183369803`, `sub_1186544726`, `sub_1189891322`, `sub_1194090570`
* probe files don't contains session ids
  * `sub-1183369796`
* some subjects contain only one file, no probes.
  * `sub-1171903426`, `sub-1172968419`, `sub-1172969386`, `sub-1175512776`, `sub-1176214854`, `sub-1177693335`,  `sub_1181314060`, `sub-1182593224`, `sub-1189891315`, `sub-1194090563`
* main file name includes `acq-FINAL`
  * `sub-1171903426`, `sub-1172968419`, `sub-1172969386`, `sub-1175512776`, `sub-1176214854`, `sub-1177693335`, `sub-1181585601`, `sub-1182593224`, `sub-1183369796`, `sub-1189891315`, `sub-1194090563`, `sub-619296`, `sub-620333`, `sub-620334`, `sub-625545`, `sub-625554`
* contains nested directory for session:
  * `sub_1171903433`, `sub_1172968426`, `sub_1172969394`, `sub_1174569641`, `sub_1175512783`, `sub_1176214862`, `sub_1177693342`, `sub_1181314060`, `sub_1181585608`, `sub_1182593231`, `sub_1183369803`, `sub_1186544726`, `sub_1194090570`, `sub_1189891322`, `sub_1194090570`
* contains two main files, one with `image+` and one with `-acq-FINAL-`
  * `sub-1181585601`
* contains twice the amount of probe files, half contain `FINAL`
  * `sub-625554`, `sub-630506`, `sub-631570`, `sub-633229`, `sub-637484`
* probe files contain `FINAL`
  * `sub-625555`, `sub-630507`, `sub-631510`
* contains three main files. one with `acq-FINAL_ogen`, one with `_ogen` and one with neither
  * `sub-625554`
* missing three probe files?
  * `sub_1181585608`

**Comment by rcpeene** [comment]
**Dendritic Coupling**

* `sub-641998_ses-1231968197-acq-1232748737-raw-movies_ophys.nwb` in highest level directory for some reason
* `sub-621602` contains a seemingly extra file? `sub-621602_ses-1194555869-acq-1194754131_image+ophys.nwb`

**Comment by Ahad-Allen** [comment]
All fixed, :)
