### ISSUE TITLE
Duplicate file?

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/OpenScopeNWB#185]
These two files from my metadata table have a suspicious subject name which ought to be revised. But I noticed also, that they seem to have identical entries except for the file size and dandi identifier. Are they copies?

![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/23059582/efee34fc-d843-43bf-a710-d5b4d9793aa0)

**Comment by Ahad-Allen** [comment]
All files were reprocessed and uploaded, this is fixed
