### ISSUE TITLE
Add stim template for sequence learning

### ISSUE THREAD

**Issue by Ahad-Allen** [AllenInstitute/OpenScopeNWB#194]

**Comment by Ahad-Allen** [comment]
All non-raw files have their templates added. The raw files are in progress of being uploaded. After finishing, we should validate that all files are up and then delete the old files with no templates to prevent doubling up of data.

**Comment by jeromelecoq** [comment]
Some raw NWB files do have the template but not the raw. 
All non-raw have the template.
