### ISSUE TITLE
Add error catch for 10,000 NaN values and logging to ensure that session is a dendritic plane.

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#34]

**Comment by jeromelecoq** [comment]
@Ahad-Allen to associate this ticket with PR to review this

**Comment by Ahad-Allen** [comment]
This should be resolved when the current branch being used for Ophys Raw info and uploads is merged.

**Comment by jeromelecoq** [comment]
See #56 for updates. PR coming
