### ISSUE TITLE
Diagnose why experiment 1211453853 has no valid roi in the cell specimen table.

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#35]

**Comment by jeromelecoq** [comment]
@jeromelecoq to confirm that it is a dendritic layer

**Comment by jeromelecoq** [comment]
@Ahad-Allen look into how to make the NWB code STILL function when all ROI as invalid

**Comment by Ahad-Allen** [comment]
Will run session once more to verify source of error and work from there

**Comment by jeromelecoq** [comment]
![Image](https://user-images.githubusercontent.com/2491343/195920370-8d7cf8c3-5e5f-4987-b23b-4af789171e07.jpg)

Yes this is a dendritic plane. See how no circular structure (somas) is present, and only "straight lines"?
