### ISSUE TITLE
Update NWB for ephys to add trial information.( Add trial information row by row and use indexed insertion for array information) (Potentially need to add image path list here rather than using the sweep_table)

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#36]
We need to add information for images list.

**Comment by jeromelecoq** [comment]
@Ahad-Allen to ask Hyeyoung if this is blocking her.

**Comment by Ahad-Allen** [comment]
Hyeyoung says this problem is not blocking, but she would like it to double check her analysis.

**Comment by jeromelecoq** [comment]
@Ahad-Allen will use https://github.com/AllenInstitute/openscope_databook/issues/19 as an opportunity to fix this.

**Comment by jeromelecoq** [comment]
@Ahad-Allen will start working on implementing this.

**Comment by jeromelecoq** [comment]
@Ahad-Allen will summarize how he will tackle this here.

**Comment by jeromelecoq** [comment]
@Ahad-Allen will check visual behavior NWB on templates for images in stim.

**Comment by Ahad-Allen** [comment]
Looking over the template section of these NWB files, I think this could be more or less what we want. 


![Image](https://user-images.githubusercontent.com/87045911/201402664-22746231-aa11-4824-b160-3a5df3739c77.png)

There is a control_description field here used to store image names, and the data field which stores the image info for each of these names. We should be able to map the info from image_path_list to a similar template and then external users should be able to map from the stim_table's image number to the templates.

**Comment by jeromelecoq** [comment]
@Ahad-Allen will modify modules in the SDK to add images template and incorporate it in OpenScopeNWB. Make a subfolder for this project

**Comment by jeromelecoq** [comment]
So @Ahad-Allen will try to add an additional object with the template on one NWB files, Send it to Hyeyoung for review and we will iterate from there.

**Comment by Ahad-Allen** [comment]
The ophys stimulus template in the SDK is designed to use the stim names and pkl file from the visual coding project. The best way to instead do this is using add_stimulus_template from pynwb over the pkl file. Currently working on a solution using this,

**Comment by jeromelecoq** [comment]
Ahad to make a branch to start the addition of that info.

**Comment by Ahad-Allen** [comment]
This branch for the openscopenwb is tracking this: https://github.com/AllenInstitute/OpenScopeNWB/tree/feature-ephys_templates, I think the best way to handle this is not directly modifying the SDK since it will be project specific changes.

**Comment by Ahad-Allen** [comment]
I was able to generate the templates and some of the data for the presentations! 

![Image](https://user-images.githubusercontent.com/87045911/225705915-0dba473d-a3ea-46c8-9da0-261435e864e3.png)

All that remains is some of the info for the presentation table. I believe the unwarped images part is just the indexed list of images, while the timestamps will need to be pulled from pickle

**Comment by jeromelecoq** [comment]
@Ahad-Allen will check if presentation is needed
then generate NWB files with templates and check that they validate.
Once that done, we need to upload all illusion back up.

**Comment by jeromelecoq** [comment]
@Ahad-Allen confirmed that presentation is not needed. 
We need to add script to reupload queue. 
@Ahad-Allen will ask hyeyoung to check that the template info is accurate.

**Comment by Ahad-Allen** [comment]
Just waiting on hyeyoung's feedback for this now :)

**Comment by Ahad-Allen** [comment]
Hyeyoung got back to me! She is having an issue with the file in matnwb and is going to send me the error stack so I can investigate that. Otherwise, she seemed okay with regenerating the files and doing a v1 release!

**Comment by Ahad-Allen** [comment]
Error using types.util.checkUnset (line 13)
Unexpected properties {data_offset}.

Your schema version may be incompatible with the file.
Consider checking the schema version of the file with
`util.getSchemaVersion(filename)` and comparing with the YAML
namespace version present in nwb-schema/core/nwb.namespace.yaml

Error in types.core.IndexSeries (line 35)
            types.util.checkUnset(obj,
            unique(varargin(1:2:end)));

Error in io.parseGroup (line 85)
    parsed = eval([Type.typename '(kwargs{:})']);

Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);

Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);

Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);

Error in nwbRead (line 59)
nwb = io.parseGroup(filename, h5info(filename), Blacklist);

**Comment by jeromelecoq** [comment]
@Ahad-Allen and @rcpeene to put together a simple notebook to help hyeyoung get unstucked so that we can apply this patch to all files prior to publication for Hyeyoung.

**Comment by jeromelecoq** [comment]
Currently failing validation to upload. Ahad will modify code to fix errors and validate.

**Comment by Ahad-Allen** [comment]
Hyeyoung gave the following feedback on the uploaded sessions:


![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/87045911/58b0e978-a565-408e-a4b1-3be78c1aa694)

**Comment by jeromelecoq** [comment]
Jerome to weight on how to do this.

**Comment by Ahad-Allen** [comment]
Hyeyoung had the following error when trying to accesss some of the blocks: 
ImportError                               Traceback (most recent call last)

<ipython-input-3-2fd5303c7703> in <module>

      1 import matplotlib.pyplot as plt

      2 from dandi import dandiapi

----> 3 from nwbwidgets import nwb2widget

      4 from pynwb import NWBHDF5IO

 

~/opt/anaconda3/lib/python3.7/site-packages/nwbwidgets/__init__.py in <module>

      1 import plotly.io as pio

      2 

----> 3 from .panel import Panel

      4 from .version import version as __version__

      5 from .view import default_neurodata_vis_spec, nwb2widget

 

~/opt/anaconda3/lib/python3.7/site-packages/nwbwidgets/panel.py in <module>

     15     list_dandiset_files,

     16 )

---> 17 from .view import nwb2widget

     18 

     19 

 

~/opt/anaconda3/lib/python3.7/site-packages/nwbwidgets/view.py in <module>

     25 from .ecephys import ElectricalSeriesWidget, show_electrodes, show_spike_event_series

     26 from .file import show_nwbfile

---> 27 from .icephys import IVCurveWidget, show_sweep_sequences

     28 from .image import (

     29     ImageSeriesWidget,

 

~/opt/anaconda3/lib/python3.7/site-packages/nwbwidgets/icephys.py in <module>

      9 from ndx_icephys_meta.icephys import SweepSequences

     10 from plotly.subplots import make_subplots

---> 11 from pynwb.icephys import SequentialRecordingsTable

     12 

     13 from .base import GroupingWidget, lazy_show_over_data

 

ImportError: cannot import name 'SequentialRecordingsTable' from 'pynwb.icephys' (/Users/hyeyoung/opt/anaconda3/lib/python3.7/site-packages/pynwb/icephys.py)

**Comment by rcpeene** [comment]
Google colab is insufficient here because it would require some environment setup for dandi and nwbwidgets. We advised hyeyoung to change her pynwb and nwbwidget versions

**Comment by jeromelecoq** [comment]
@Ahad-Allen to send reminder

**Comment by jeromelecoq** [comment]
Hi Jerome,
 Thank you so much for your prompt response. I'm sorry I haven't been so prompt myself. I responded to Ahad. Currently it seems that the nwb2widget only contains stimulus info about the IC blocks. The sizeCI block and RFCI block images are missing. Hope this helps.
Best,

**Comment by Ahad-Allen** [comment]
I was able to add the sizeCI and RFCI blocks to the template section of the file! They were originally not added because I ran a check with the image folder and the stimulus presentations for naming, to avoid accidentally adding images that should not be present. In the image folder, the names of sizeCI and RFCI were capitalized differently from inside the nwb file, causing them to get skipped. if they data there looks good we can do this for all of hyeyoung's files and reupload :)

**Comment by Ahad-Allen** [comment]
We noticed yesterday that only image per a presentation was added to the nwb file, but that was caused by the add_to_nwb_ function being indented out by 1 tab relative to the for loop for the image addition. This is resolved and we now seem to have all the images added to the nwb files correctly!

**Comment by jeromelecoq** [comment]
Hyeyoung agreed to our change
