### ISSUE TITLE
Finish behavior agnostic PR for the SDK

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#37]
Ahad to add description here

**Comment by jeromelecoq** [comment]
Once your have understood 2p raw data addition. Perhaps making a new PR for this would be good.

**Comment by jeromelecoq** [comment]
@Ahad-Allen to talk to Adam about this.

**Comment by Ahad-Allen** [comment]
I've messaged Adam about his suggestions for the best way to handle the PR and which branch to merge into.

**Comment by Ahad-Allen** [comment]
Adam responded by suggesting that the best way to handle this is attempting to merge my branch into main. it is likely that there will be merge conflicts doing so, but he is willing to dedicate some time to help me clear those.

**Comment by Ahad-Allen** [comment]
Created a PR here https://github.com/AllenInstitute/AllenSDK/pull/2664. Per the allenSDK's guidelines there will be some minor changes I need to implement (Mostly creating a unit test for the non-behavior ophys session), and I will need Adam's help with some merge conflicts. I will update this ticket based on the results of that. Additionally, I think we will need to try converting a behavior-based ophys session to make sure none of my changes are breaking

**Comment by jeromelecoq** [comment]
Ahad to ask status on this to the team. Whether they still plan to rewrite

**Comment by Ahad-Allen** [comment]
Contacted the team and was informed a rewrite is still in the backlog

**Comment by jeromelecoq** [comment]
This will not be merged so closing
