### ISSUE TITLE
Document use and underlying process to upload NWB files using web portal

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#38]

**Comment by jeromelecoq** [comment]
This is potentially a large item. We will focus on documenting our repositories first. Including our web tools.

**Comment by jeromelecoq** [comment]
Ahad to add feedbacks to improve document. 
Add link to doc here.

**Comment by Ahad-Allen** [comment]
https://alleninstitute.sharepoint.com/:w:/s/OpenscopeU24/EWA5SP8rq_tHlhL7vX7CrFUBIAcfxpU0LdvjiYXqhYB0vA?e=XguJ8s

**Comment by rcpeene** [comment]
I gave Ahad some clarifying feedback which he is working on.

**Comment by Ahad-Allen** [comment]
Updated doc based on Jerome's feedback :)

**Comment by Ahad-Allen** [comment]
Updated the doc, i think it is ready for @jeromelecoq to review :)

**Comment by jeromelecoq** [comment]
Looks great! I added more comments. I think the main thing left is to add more details on the web portal. I did not understand why this document should not cover it as well. We have to do it anyway. 

Thanks!

**Comment by jeromelecoq** [comment]
There is comment left to address. I just went through it.

**Comment by Ahad-Allen** [comment]
The comment has been addressed. i think we are done! :)

**Comment by Ahad-Allen** [comment]
Shared the doc with the working group!

**Comment by arjunsridhar12345** [comment]
information on those was very helpful!
