### ISSUE TITLE
Convert session with dropped frames : 1214523350

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#42]
This session had dropped frames in the stimulus data. We are trying conversion of NWB. 
An antivirus is causing this issue. 
We want to check with external teams whether the file is sufficient for analysis.

**Comment by Ahad-Allen** [comment]
File appear to have generated successfully, at least. Can discuss output during standup today

**Comment by Ahad-Allen** [comment]
messaged team about reviewing. Starting upload now

**Comment by Ahad-Allen** [comment]
Moving this to external as we await dandi team feedback

**Comment by jeromelecoq** [comment]
@Ahad-Allen to ping them for update

**Comment by jeromelecoq** [comment]
@jeromelecoq to follow up on slack with them

**Comment by jeromelecoq** [comment]
I followed up on slack. I think they have understood the issue and properly investigated it.

**Comment by jeromelecoq** [comment]
I followed up on slack. I think they have understood the issue and properly investigated it.
