### ISSUE TITLE
Begin work on adding raw data to ophys nwb files

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#43]

**Comment by jeromelecoq** [comment]
1. Current failing as it copies the data. 
2. Current on a branch. @Ahad-Allen to link the branch to this issue.

**Comment by jeromelecoq** [comment]
1. @Ahad-Allen to add link to compression algorithm used here. 
2. File is stored on Allen network folder. Ahad to look this here
3. @Ahad-Allen will try uploading to Dandi. 
4. @Ahad-Allen to check how it is chuncked in the NWB/HDF5 file. 
5. @Ahad-Allen will also check upload time and benchmark.

**Comment by Ahad-Allen** [comment]
1. info on gzip/nwb can be found here https://pynwb.readthedocs.io/en/stable/tutorials/advanced_io/h5dataio.html#dynamically-loaded-filters and here https://www.gnu.org/software/gzip/manual/gzip.html
2. File is at /allen/programs/mindscope/workgroups/openscope/ahad/ophys_no_behavior_nwb/ophys_dandi
3. This is currently running

**Comment by Ahad-Allen** [comment]
3./5. The file is up here: https://dandiarchive.org/dandiset/000336/draft/files?location=1214523350%2F. The remote upload is much faster than the local. I am not sure if this is just because of the function I chose, but I will investigate a bit more(Internet speed limits are almost certainly a factor as well). The upload was done when I opened the command line 30 minutes after starting.

**Comment by jeromelecoq** [comment]
Raw data is currently added under acquisition as "raw_data":

![Image](https://user-images.githubusercontent.com/2491343/198735292-6bfb1c2a-e35c-4a8e-8f9d-8e4aea09369d.png)

This is rather unspecific and should be perhaps better standardized. 
@Ahad-Allen is looking into whether there is a better standard. 

It seems to be working properly.

**Comment by jeromelecoq** [comment]
Chuncking is appropriate : 


![Image](https://user-images.githubusercontent.com/2491343/198735567-90445beb-9c36-4e13-a825-a339d1828a55.png)

**Comment by jeromelecoq** [comment]
And number of frames (44212) matches the other datasets so all points as this being correct.

**Comment by Ahad-Allen** [comment]
The standard for naming appears to be to name a subfolder within acquisitions DynamicTable. The actual name for the raw within that seems to be up to us.

**Comment by jeromelecoq** [comment]
@Ahad-Allen found a motion-correction standard for storing. Will use this.

**Comment by jeromelecoq** [comment]
@Ahad-Allen meeting with Ben tomorrow to discuss convention

**Comment by rcpeene** [comment]
A notebook showing how to handle what exactly? Compressing a file with ZTSD?

**Comment by Ahad-Allen** [comment]
> A notebook showing how to handle what exactly? Compressing a file with ZTSD?

Yes. I believe that ZSTD needs to be imported, so this could be helpful for end users.

**Comment by jeromelecoq** [comment]
Related to #56. See updates there
