### ISSUE TITLE
Resolve issue with LFP times not being in seconds.

### ISSUE THREAD

**Issue by Ahad-Allen** [AllenInstitute/OpenScopeNWB#46]
Currently, the LFP times in ephys NWB files are not being displayed in seconds. This may be related to the align timestamps module. I believe they are being input into the JSOn correctly, so perhaps this is a result of me not using the output from the output json correctly.

**Comment by jeromelecoq** [comment]
@Ahad-Allen needs to update Glo LFP files for timing info

**Comment by jeromelecoq** [comment]
@rcpeene solved this problem. The data was there.

**Comment by jeromelecoq** [comment]
@rcpeene will also share the fix with Jake Westerberg on slack

**Comment by rcpeene** [comment]
In the nwb files I explored, as per the [PyNWB specification](https://pynwb.readthedocs.io/en/stable/pynwb.ecephys.html), the lfp electrical series array also comes with a _timestamps_ array. The indices of the timestamps array correspond to the indices of the electrical series measurements.

**Comment by Ahad-Allen** [comment]
Will need to reupload the older sessions, as they were not run through the align-timestamps module correctly. This seems to be the source of the problem.

**Comment by Ahad-Allen** [comment]
Will work with Carter today to confirm the regenerated GLO files work with his analysis for timestamps.

**Comment by Ahad-Allen** [comment]
Carter and I met and confirmed the new GLO files look appropriate.

**Comment by rcpeene** [comment]
Is this good to close @Ahad-Allen ?

**Comment by Ahad-Allen** [comment]
I think we can close this!
