### ISSUE TITLE
Resolve frame time sync issue

### ISSUE THREAD

**Issue by Ahad-Allen** [AllenInstitute/OpenScopeNWB#47]
Note: This is technically a problem with the SDK, but I am listing it as an OpenScopeNWB issue for the sake of convenience.

I met with Corbett briefly about the sync issue and it appears to be causing the SDK's fix_unexpected_edges syncing function to fail. I am currently looking over the code for this to get a better idea of how to approach the problem and Corbett is working on plotting the sync timings to see if we can fix this by using some quick and dirty assumptions about the timing between edges. I will update this issue depending on what solution seems to be the best option when he is done doing so.

**Comment by Ahad-Allen** [comment]
I spoke with Corbett about the problem. We suspect that only LONG times between edges cause this problem with fix_unexpected_edges, so we are investigating whether simply ignoring times that are long by a certain amount would resolve this problem. I am going to plot some sessions and see if other long times that get removed are common. Also, we will need to try conversion for several other sessions to validate that this change to the SDK does not break compatibility. .

Reproducibility is an important goal of the OpenScope project and whatever changes we do to the sdk must be noted and stored. If the changes appear to not cause any problems for other sessions or future problems, we should handle this by submitting a PR for the SDK and using the updated version moving forward. In the event that this ends up being an appropriate solution for these specific sessions but not an ideal change to implement generally, these changes should be stored as a branch of the SDK with this change being noted in the metadata associated with the sessions.

I am of the opinion that lot of testing involving conversion for several projects should be done to decide the best approach moving forward to validate that edge cases other sessions experienced are not broken by this change. The ideal way to select which sessions to convert, how to convert them, and how to to determine if compatibility has been broken is not currently clear to me, but I think it is a very non-trivial consideration.

**Comment by Ahad-Allen** [comment]
The affected session for Illusion is currently missing a D2 upload, but we can try converting it after that has been done. In the mean time, I've analyzed the plots for the other sessions and found that they all show similar behavior with long frame times specifically. Based on jerome's suggestion, I will be adding a flag to the bash script to trigger an alternative job using a branch of the allensdk with the fix_unexpected_edges function changed to ignore these longer syncs. At least for now.

**Comment by Ahad-Allen** [comment]
Discovered two different ways to handle the problem, we will need to investigate which is the best solution. In the meantime, however, we at least know that the problem has some fairly simple patches that can be done for this use case alone.

**Comment by Ahad-Allen** [comment]
Here is a screenshot of the current process being used to plot diodes:


![Image](https://user-images.githubusercontent.com/87045911/195674474-74d1d75e-7853-4cf9-94fe-90262439cd4e.png)

**Comment by jeromelecoq** [comment]
1. @Ahad-Allen will add a session list checker to apply this fix to these sessions and run NWB conversion. 
2. @Ahad-Allen will add an error exception for future session whenever the fixed diode code output a different timing information from the normal diode timing.

**Comment by Ahad-Allen** [comment]
Exception list and alternative conversions are done. Working on the exception gen for other sessions and then making this into a pr.

**Comment by Ahad-Allen** [comment]
I think I have the exception test working! Just need to test and then I can commit and create the pr.

**Comment by jeromelecoq** [comment]
@Ahad-Allen to add error status on web portal and ability to access log.

**Comment by Ahad-Allen** [comment]
Using the basic pr at https://github.com/AllenInstitute/openscopedataportal_back/pull/2 to allow for error status to be shown.

**Comment by Ahad-Allen** [comment]
All the functions and such are written for this, I am waiting on the uploads of the GLO data sessions to test this my fix with their data. The fix appears to work for the illusion data, however. Will issue a PR when I can confirm the firebase pull and test works as expected with those sessions (there is currently no "directory" field for the GLO sessions on LIMS, so I cannot test the automation of the script with them.)

**Comment by jeromelecoq** [comment]
@Ahad-Allen will follow up with the neuropixel team, perhaps mid-week regularly. We expect to monitor this closer to experiment data collection.

**Comment by Ahad-Allen** [comment]
Sev is sick today, will meet with her tomorrow. Ben told me he can get the D2 uploads for these files done today, so just the CCF should remain.

**Comment by Ahad-Allen** [comment]
I trained Sev on generating the CCF files, so we should be good to go on this soon!

**Comment by Ahad-Allen** [comment]
There is a rig issue with generating CCF files due to some backlog with Sev. Will message ben about triggering D2 without the CCF to generate these files with placeholder ccf.

**Comment by Ahad-Allen** [comment]
The CCF for the final illusion is done and Ben is working on uploads. We should be able to test this!

**Comment by Ahad-Allen** [comment]
Severine worked on some more CCF uploads but had an issue with the generation of one, I was able to use my script with her inputs to fix this however. I asked her to send the inputs for the other sessions she intends on uploadings, and I will just run the script for her for these. I think the issue might be related to her being on windows, so I will create an issue and look at that. In the meantime, I will handle CCF registrations for the other sessions she has the inputs ready for.

**Comment by jeromelecoq** [comment]
@Ahad-Allen will push forward one session that is both showing this issue and was processed.

**Comment by jeromelecoq** [comment]
Waiting on Ben to upload CCF

**Comment by jeromelecoq** [comment]
@Ahad-Allen will test today given that we have one file

**Comment by Ahad-Allen** [comment]
The Sync Script seems to correctly identify when a file has the long frames, so I am just working on getting this automated into the pipeline for it. We should run this and mark the error on firebase, before conversion I think

**Comment by Ahad-Allen** [comment]
After speaking with @jeromelecoq today, we decided the best way to handle this was to run an alternative branch of the SDK for the sessions where the long frames exist. This is tracked by #75
