### ISSUE TITLE
Update dandi upload for ophys to generate folders for sessions

### ISSUE THREAD

**Issue by Ahad-Allen** [AllenInstitute/OpenScopeNWB#48]
Currently, the dandi upload generates a folder for each EXPERIMENT for dandi rather than one for each session. This needs to be resolved to prevent very cluttered dandisets.

**Comment by jeromelecoq** [comment]
@Ahad-Allen to add code commit to this

**Comment by Ahad-Allen** [comment]
Commit https://github.com/AllenInstitute/OpenScopeNWB/commit/539da539d61b04ced2564e7ceff40618713fbbdc has resolved this. Will be handled with the dandi upload pr
