### ISSUE TITLE
NWB files currently contain CCF area but not layer

### ISSUE THREAD

**Issue by Ahad-Allen** [AllenInstitute/OpenScopeNWB#53]
Currently, the location info for each probe in the nwb files indicates the area of the brain the probe is in, e.g. VISp, but not the layer (e.g. VISp2

**Comment by jeromelecoq** [comment]
@Ahad-Allen explain the fix here.

**Comment by Ahad-Allen** [comment]
Not yet implemented but I believe this is because the numbers associated with each area get filtered out before being input into the nwb files during the write_nwb module. I will investigate and confirm today.

**Comment by Ahad-Allen** [comment]
This is correct. This specific line in ecephys modules is doing this:
`        numbers = re.findall(r'\d+', structure_acronym)
`

**Comment by Ahad-Allen** [comment]
This should be resolved with the latest commit for conversions. WIll confirm when looking at the data with Carter

**Comment by Ahad-Allen** [comment]
Layers seem to be correct now! I can regen the appropriate files when the image_path changes are done.

**Comment by jeromelecoq** [comment]
@Ahad-Allen will provide commit number here

**Comment by Ahad-Allen** [comment]
Resolved with 13a1267844b7630908b3eb41868613c9356a2909
