### ISSUE TITLE
Run final experiment of illusion project through NWB conversion

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#54]
A few illusion experiment are still not uploaded to Dandi.

**Comment by jeromelecoq** [comment]
4 experiments waiting from some files.

**Comment by Ahad-Allen** [comment]
Final 2 are waiting for D2 now.

**Comment by Ahad-Allen** [comment]
Still waiting on resorting for the 2 sessions that have d2 but the wrong probe info

**Comment by jeromelecoq** [comment]
@Ahad-Allen meeting with Sev today to figure out holding up items.

**Comment by Ahad-Allen** [comment]
Sev is sick today, will meet with her tomorrow. Ben told me he can get the D2 uploads for these files done today, so just the CCF should remain.

**Comment by jeromelecoq** [comment]
There is a longer lead time to do CCF registration. As a result, we will do a D2 upload with placeholder for location in the NWB. Ahad will then convert and upload to Jake for analysis.
We will do a second upload when CCF is available.

**Comment by jeromelecoq** [comment]
Ben is starting D2 today. 
Sev started some CCF registration. She did one.

**Comment by Ahad-Allen** [comment]
We discussed the details of LFP generation with Jake and decided to move forward with the larger LFP files for his project. I will trigger a conversion once the D2 upload is done (it may already be done, i will check) and see if the sync catch works with the data and placeholder CCF.

**Comment by jeromelecoq** [comment]
@Ahad-Allen will follow up with Ben

**Comment by Ahad-Allen** [comment]
Ben found some issues with the upload and QC process, which resulted in folders sometimes not having metrics files, sorted probe files etc. In the future, sessions like this will automatically be marked if they don't have these files and this shouldn't be an issue. In addition, only two of the sessions had been properly QC'd, 
    1212569512_637909_20220920

    1211241460_637542_20220915
which have been uploaded. Ben is working with Corbett to get the QC pipeline triggered for the other session and will upload them once they have been done. One of the sessions that Ben uploaded has the frame time issue, so this is a good chance to finally test our code!

**Comment by jeromelecoq** [comment]
@Ahad-Allen will push forward one session that is both showing this issue and was processed.

**Comment by Ahad-Allen** [comment]
I contacted Sev and Ben with our weekly email today and am just waiting for a response to see if the QC pipeline issue was fixed. Also, I generated the CCF files for some sessions and they should be able to be uploaded now. I think we are approaching the end for this project :)

**Comment by jeromelecoq** [comment]
Let's use a placeholder for coord for now.

**Comment by Ahad-Allen** [comment]
Running conversions for the last sessions now, as all D1 and D2 are done. Sev also did 3 more CCF this morning, though I need to check if they are for this project or illusion

**Comment by Ahad-Allen** [comment]
I am re-running the conversions for the older illusion sessions to get them up to data and will then upload them all to dandi! All d1, d2, and ccf uploads seem to be done for all sessions in this project now.

**Comment by Ahad-Allen** [comment]
Spoke with @jeromelecoq about this yesterday and we are going to change the upload process to automate this a little more for ecephys and fully automate it for ophys. For ophys we can track the workflow status for this to see if all files are up, and for ecephys I am going to add the conversion status and location to firebase to allow it to upload automatically.

**Comment by jeromelecoq** [comment]
Experiment were uploaded manually. Currently checking for consistency.

**Comment by Ahad-Allen** [comment]
The files seem good! I am pinging Hyeyoung to let her know they're up.
