### ISSUE TITLE
Modify file path convention to store NWB files on DANDI for EPHYS.

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#55]
This is similar to #69

**Comment by Ahad-Allen** [comment]
I can confirm this is covered with the https://github.com/AllenInstitute/OpenScopeNWB/pull/67 pr. The dandi ecephys upload function makes sure to write the nwb in a folder with the path of sub -> sess/probes

**Comment by jeromelecoq** [comment]
Is that convention following exactly what the Dandi standard upload does? For other datasets, I see 
"In_vivo/sub-1704191rm/sub-1704191rm_ses-1704191rm-2-1,2-1_icephys.nwb"
for example

**Comment by Ahad-Allen** [comment]
I updated this to more accurately reflect the dandi structure of sub_subject_id/sub_subject_id+sess_id_type.nwb. I will add this commit to the next PR we do and handle all uploads with this path in the future.

**Comment by jeromelecoq** [comment]
@Ahad-Allen will have to delete old files with previous formatting path.
