### ISSUE TITLE
Implement flag in NWB conversion to add RAW data for 2p

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#56]

**Comment by Ahad-Allen** [comment]
This is intended to allow us to specify whether we want to generate an NWB with the RAW data.

**Comment by Ahad-Allen** [comment]
https://github.com/AllenInstitute/OpenScopeNWB/commit/253a59c040f8a9aae194aa4ea432e0fc92152533 Should resolve this

**Comment by Ahad-Allen** [comment]
I will be meeting with Ben from the NWB team about best practices for uploading raw 2p data this week. I will update if there are any large changes we need to do to follow best practices.

**Comment by jeromelecoq** [comment]
@Ahad-Allen will make a PR after the meeting

**Comment by Ahad-Allen** [comment]
Currently working on moving the time series to a 2 photon series based on Ben's feedback. The only current issue seems to be saving the current plane as a dandi plane, as this is an expected input for the series.

**Comment by jeromelecoq** [comment]
Ahad needs to make the raw data associated with plane into an Imaging plane object in NWB. Additional information on calcium indicator, brain area. 

Ahad to send list of missing keys/values to Jerome

**Comment by Ahad-Allen** [comment]
Jerome sent me the missing values. Finishing implementing this now.

**Comment by Ahad-Allen** [comment]
There's a slight issue with the file naming and download folder being incorrect. Moving the write location to the openscopedata folder and storing that result to make automated uploads.

**Comment by Ahad-Allen** [comment]
There was a weird problem with the uploads here. The dandiset is marked as having been updated but the files are not present on it. I am going to invesitigate the upload functionality and manually trigger it for a session to see what's going on here.

**Comment by jeromelecoq** [comment]
@Ahad-Allen to check local logs for upload.

**Comment by jeromelecoq** [comment]
@Ahad-Allen will create a branch associated with non-upload code and have it be a PR.

**Comment by Ahad-Allen** [comment]
Figured out the upload issue and resolving now. Will also split into two branches for the PR.

**Comment by Ahad-Allen** [comment]
These changes were implemented with the latest commit forcing the dandi upload to use the same environment as the ephys generation. This essentially forces the entire project onto the same env, other than the ophys generation which currently uses an alternative version of the allensdk. Once the SDK is merged with our branch, everything should be able to run on the same environment without issue. Additionally, many files were generated and pushed to dandi today, with Raw versions of them currently running. I am creating a draft PR now that I will change to a full PR once I finish some linting.

**Comment by Ahad-Allen** [comment]
Associated with pr #67

**Comment by Ahad-Allen** [comment]
Raw conversion and Uploads are working now with the imaging plane being pulled from what is already generated by the SDK in the processing field. @rcpeene is looking over the files now to see if the change to two_photon series instead of time_series for the raw data works for nwbwidget analysis

**Comment by jeromelecoq** [comment]
We decided to move forward with uploading all session/all experiments to dandi with this system. Both raw and non-raw

**Comment by Ahad-Allen** [comment]
Jay said he will be looking at the files tonight and giving feedback on them!
