### ISSUE TITLE
Delete local NWB file with large raw data after upload

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#57]

**Comment by Ahad-Allen** [comment]
The raw files generated by the conversion process can be over 160 gigs per session, we want to delete them after uploads are done to avoid terabytes of data on the local servers.

**Comment by Ahad-Allen** [comment]
We will likely also want to delete local LFP files if we continue to generate ones with all the channel info. This would be based on Jake's feedback.

**Comment by Ahad-Allen** [comment]
Resolved with https://github.com/AllenInstitute/OpenScopeNWB/commit/46407eb96653cead4f376b8b9f09ba29c2cbcb55
