### ISSUE TITLE
Look into redundant data fields in acquisition lfp data

### ISSUE THREAD

**Issue by Ahad-Allen** [AllenInstitute/OpenScopeNWB#60]
@rcpeene Noted that there seem to be two fields in the NWB files associated with the LFP data. I will look into removing this redundancy.

**Comment by rcpeene** [comment]
There are indeed two ways to access the LFP data (though they point to the same array in memory, so not wasted space). This creates a lit bit of confusion. Will ask Ben or look through the specs to see if this is standard or we are converting wrong.

**Comment by rcpeene** [comment]
According to Ben, the syntax like `nwb.acquisition["lfp"].electrical_series["probe_0"] is most appropriate for the standard to access the LFP time series. This is a bit more verbose but, since nwb.acquisition["lfp"] is a PyNWB.LFP object, it is clearer and more machine-readable.
