### ISSUE TITLE
Create spreedsheet to track ophys uploads

### ISSUE THREAD

**Issue by Ahad-Allen** [AllenInstitute/OpenScopeNWB#62]
As we continue to upload more sessions, it is important that we keep track of which ones have been uploaded and which ones remain. Perhaps something like ecephy's LIMS tracker sheet is the best option here.

**Comment by jeromelecoq** [comment]
Let's do it. Eventually the Goal is to use the data portal for this.

**Comment by Ahad-Allen** [comment]
Started today. I will use this to track all uploads until the website is a little more usable.

**Comment by jeromelecoq** [comment]
Can you add a link to spreadsheet here?

**Comment by Ahad-Allen** [comment]
https://alleninstitute-my.sharepoint.com/:x:/g/personal/ahad_bawany_alleninstitute_org/EZf1zu1E_hRPss7eFTk9-H4Buo7yG604JGQbqKGMg_E6qA?e=j7RsRb
