### ISSUE TITLE
Ecephys data in illusion has no valid ccf coordinates

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/OpenScopeNWB#64]
I'm attempting to debug some issues with rendering Neuropixel CCF coordinates. On the data I have looked at, the CCF coordinates are all -1. Specifically in this file `sub-1171903426/sub-1171903426_ses-1181330601_probe-0+1+2+3+4+5_obj-1qn79il.nwb`

**Comment by rcpeene** [comment]
This file `sub-1171903426/sub-1171903426_ses-1181330601_probe-0+1+2+3+4+5_obj-12ryxgg.nwb`, however, is good (but the data still need to be scaled up by 1000 as mentioned here #51 )

**Comment by Ahad-Allen** [comment]
This seems to have been a result of the placeholder info, as explained in a similar case with #77
