### ISSUE TITLE
Meet with Jake about ecephys LFP parameters

### ISSUE THREAD

**Issue by Ahad-Allen** [AllenInstitute/OpenScopeNWB#65]
I tested the new ecephys upload and got the process working. Jake's files are up at https://dandiarchive.org/dandiset/000253/draft/files?location=1180116198 and he has agreed to meet so we may discuss options for future data creation today. This will help us decide how to handle the large resource usage that LFP files using all channels generate.

**Comment by jeromelecoq** [comment]
Carter will also present his LFP notebooks for feedbacks

**Comment by Ahad-Allen** [comment]
Meeting with Jake, we decided to continue generating the larger LFP files for his project. He will work on creating some quantitative analysis to show the differences between the two types of files. @rcpeene will share details on what Jake mentioned for the notebooks

**Comment by rcpeene** [comment]
Jake's feedback on LFP notebook to show up [here](https://github.com/AllenInstitute/openscope_databook/issues/19)
