### ISSUE TITLE
Change folder structure for ophys to follow conventions for dandi

### ISSUE THREAD

**Issue by Ahad-Allen** [AllenInstitute/OpenScopeNWB#69]
Change upload folder directory to follow subject -> session ->experiment structure rather than session -> experiment

**Comment by Ahad-Allen** [comment]
Tracked with #67. The code changes for this are in place now. The only structural change needed was changing the dandi output path string.

**Comment by Ahad-Allen** [comment]
I updated this to more accurately reflect the dandi structure of sub_subject_id/sub_subject_id+sess_id. I will add this commit to the next PR we do and handle all uploads with this path in the future.

**Comment by jeromelecoq** [comment]
@Ahad-Allen will try one upload once PR #75 is merged

**Comment by jeromelecoq** [comment]
One experiment had a - instead of _ in the folder structure
