### ISSUE TITLE
Make dummy dandiset?

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/OpenScopeNWB#71]
At lunch today we discussed the idea of making a dummy dandiset with small, but realistically formatted, ecephys and ophys files. This would be very useful for my usage, it would speed up a lot of my development while allowing me to work on files that act realistically.

**Comment by rcpeene** [comment]
I'm imagining a dandiset with 4 files;
1. Ophys
2. Ophys with raw
3. Ecephys
4. Ecephys with a probe/LFP

I'll try to identify specifications for the duration of these data based on the notebook's analysis limitations (like RAM usage and processing time)

**Comment by jeromelecoq** [comment]
Ahad will evaluate what is needed to cut the duration of data in the file. 
List out bullet items here. 

- One ephys NWB without LFP
- One ephys NWB with LFP
- One ophys NWB with raw
- One ophys NWB without raw

Carter to add how much time for each.

**Comment by jeromelecoq** [comment]
We agree to start with cutting spike_times from an existing file. @Ahad-Allen

**Comment by rcpeene** [comment]
Also the stim times! Those should be cut in the same way so as to keep my notebooks working.

**Comment by Ahad-Allen** [comment]
I was able to cut down the spike_times using a script. We can discuss this during the standup

**Comment by rcpeene** [comment]
For ecephys, we probably want to cut it down to 10 minutes or so. For ophys, it would also be good to cut it down to 10 minutes.

**Comment by jeromelecoq** [comment]
We discussed and decided to keep all units regardless of whether they spike during the interval or not.

**Comment by Ahad-Allen** [comment]
We discussed this yesterday, but I have the file generating all the appropriate trimmed fields now. Carter looked over the trimmed fields and they seem to work for him :)
 The problem is that the unit table columns are different from those of processing or modules and cannot be popped. The best solution here is probably going through the entire file and creating a 'clone' file with the only difference being that spike times and spike amplitudes are generated using the trimmed fields.

**Comment by Ahad-Allen** [comment]
We managed to generate a properly trimmed file, but it has errors with the "root builder". I spoke with Jerome about this and we are going to ask ryan from the pynwb team for some help on this.

**Comment by Ahad-Allen** [comment]
Ryan is going to send up an example of how to do this with h5py and pynwb's export later today :)

**Comment by Ahad-Allen** [comment]
![Image](https://user-images.githubusercontent.com/87045911/225097070-90f8c2b9-72b9-48b1-a876-17a90bbea8e0.png)

**Comment by Ahad-Allen** [comment]
Ryan responded and created this super helpful notebook! I am going to emulate what he's doing here :) https://gist.github.com/rly/d09ee3940e97dc7d13c41f48157c2465

**Comment by jeromelecoq** [comment]
We decided to not modify NWB files and instead trim the input file to generate a smaller NWB file.

**Comment by jeromelecoq** [comment]
@Ahad-Allen will chat with Adam to check whether we are not aware of an important detail there.

**Comment by Ahad-Allen** [comment]
I went over the ecephys modules, based on Adam's feedback, and didn't find any huge pitfalls. The only potential problem I see is the mean_waveforms.npy, which is inserted as a column into the nwb file, will need to be trimmed just as the spike_times will be. The only difficulty here is figuring out the exact layout of the mean_waveforms. I'll discuss this during our standup today

**Comment by jeromelecoq** [comment]
After trying this in depth, we think this is a wrong set of cost/benefit and decides to focus on other things.
