### ISSUE TITLE
Add missing dandi path to old exp manually

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/OpenScopeNWB#72]

**Comment by Ahad-Allen** [comment]
We will need to rerun dandi uploads of older files to get them displayed in the manner we wish on Dandi (in addition to making them reflect the most current nwb format we are using). I triggered all the illusion conversions today for this purpose.

**Comment by Ahad-Allen** [comment]
Spoke with @jeromelecoq about this yesterday and we are going to change the upload process to automate this a little more for ecephys and fully automate it for ophys. For ophys we can track the workflow status for this to see if all files are up, and for ecephys I am going to add the conversion status and location to firebase to allow it to upload automatically.

**Comment by Ahad-Allen** [comment]
The dandi uploads for the older illusion sessions seem to be good, so I will manually add the older paths in for these.

**Comment by jeromelecoq** [comment]
Ahad needs to push to the database, somehow it is not showing

**Comment by Ahad-Allen** [comment]
All the illusion paths are in. GLO should automatically populate as we upload them once the eye tracking is in :)

**Comment by jeromelecoq** [comment]
Ahad to check. it seems some exp were updated but not all? 

Will look into making an hyperlink

**Comment by Ahad-Allen** [comment]
I am currently adding these into the GLO sessions as well. Additionally, more info about the hyperlinking can be found here: https://github.com/AllenInstitute/openscopedataportal_front/issues/20.

**Comment by Ahad-Allen** [comment]
Updated for GLO sessions as well!
