### ISSUE TITLE
Handle eye-tracking Upload for GLO

### ISSUE THREAD

**Issue by Ahad-Allen** [AllenInstitute/OpenScopeNWB#76]
Ben Hardcastle is looking over the following sessions because their upload did not trigger the eye tracking jobs appropriately.: 

1212569512_637909_20220920
1213341633_637908_20220922
1214578117_639564_20220928
1215804658_638390_20221005
1217213788_640507_20221012
1221092548_642507_20221026
1224930300_645495_20221109

**Comment by jeromelecoq** [comment]
@Ahad-Allen will follow up this PM to check updates

**Comment by Ahad-Allen** [comment]
Ben says this seems to be because of an error with the input ecephys_upload_queue to Lims causing a failure for that step, preventing future steps from occuring such as eye tracking. He is working on resolving this.

**Comment by Ahad-Allen** [comment]
Ben has retiggered the uploads and we should have these sessions soon!

**Comment by Ahad-Allen** [comment]
Followed up with ben because some of the sessions, such as /allen/programs/mindscope/production/openscope/prod0/specimen_1196664789/ecephys_session_1212569512/, now have an eye tracking folder, but it seems to be empty. Perhaps this is because the upload is still in progress? Waiting for Ben's response to see what's going on here.

**Comment by Ahad-Allen** [comment]
Actually, looking at the job tracker on Lims, it does seem to be in progress for these eye tracking uploads. I think we should be good to convert by Monday!
