### ISSUE TITLE
One Illusion experiment has a mis-formated DAT file for LFP times

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#77]

**Comment by jeromelecoq** [comment]
Ahad to describe the problem in details here and contact the relevant person to fix the data.

**Comment by Ahad-Allen** [comment]
Sessons 1184980079 seems to have a continuous dat file that's too large? The specific error I get for this session is: OSError: expected LFP data filesize to be 18148515840 bytes, but its size was 19103341824 bytes. I've reached out to Ben and Sev about it and triggered a re-conversion just to make sure the error is repeatable

**Comment by jeromelecoq** [comment]
Write in OpenScope DataBook that LFP is corrupted here. 
And upload the rest of the data.

**Comment by Ahad-Allen** [comment]
I triggered the conversion for this session without LFP, we just need to upload once it's done.

**Comment by jeromelecoq** [comment]
Add to OPenScopeDataPortal a note about this issue and notify Hyeyoung about it. And move to resolved.
