### ISSUE TITLE
Upload Remaining 2P experiments

### ISSUE THREAD

**Issue by Ahad-Allen** [AllenInstitute/OpenScopeNWB#78]
Several sessions for 2p are ready to upload but just need to have the jobs triggered. I will trigger these conversions and uploads

**Comment by Ahad-Allen** [comment]
I triggered the non-raw conversions and uploads for several sessions and got them onto dandi. I triggered the remaining sessions but need to redo them due to an original failure caused by a minor code clean-up change I did.

**Comment by Ahad-Allen** [comment]
I will be testing the raw upload scheduler today. Essentially, we will use Slurm to ensure the code waits until the previous conversion has finished before submitting the new one. If this works, all the raw uploads should be able to be done!

**Comment by jeromelecoq** [comment]
Ahad is deleting output folder to create room to test schedule

**Comment by jeromelecoq** [comment]
All experiments are up :-)

a '+' is missing from some filenames between sessXXXX and ophys. 

@Ahad-Allen will contact ben and Satra to see if the move feature could be used to rename. Currently it does not work with embargoed datasets.

**Comment by Ahad-Allen** [comment]
Satra contacted me and informed me to add this as an issue on the dandi github.I will do so later today

**Comment by jeromelecoq** [comment]
@Ahad-Allen Ben shared more ideas. Ahad will copy here.

**Comment by Ahad-Allen** [comment]
Ben/Satra mentioned that we could use the dandi api directly to do this since it's just calling a put to the website anyway. I was able to do this successfully for all the dendrite sessions! I am going to look them over once just to confirm, but they should be good now :)
