### ISSUE TITLE
Clean up old file naming convention on Dandi

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#79]

**Comment by jeromelecoq** [comment]
@Ahad-Allen is checking glow experiments for duplicates

**Comment by jeromelecoq** [comment]
Related to #78.

**Comment by jeromelecoq** [comment]
@Ahad-Allen will also need to update the DataPortal path to Dandi

**Comment by jeromelecoq** [comment]
Waiting on Satra and Ben feedback on how to use Moving file feature with Embargeod datasets

**Comment by Ahad-Allen** [comment]
Details are on #78. Resolved by using the dandi api to fix the conventions
