### ISSUE TITLE
Should units table include location structure?

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/OpenScopeNWB#82]
In the AllenSDK examples, the units table of the NWB file includes some properties `structure_acronym` (like APN) and `structure_id` (215 for APN). These aren't included in the GLO files I saw, but they could be handy to have in some databook analysis.

**Comment by jeromelecoq** [comment]
We discussed adding this information along with the CCF notebook for probe track. This would provide a link between the peak unit location and the brain area of the node where the cell was found.

**Comment by rcpeene** [comment]
The electrodes table includes the location of each channel along the probe. This should suffice. I'll add code for this, as tracked by https://github.com/AllenInstitute/openscope_databook/issues/147
