### ISSUE TITLE
One session in illusion has inconsistent CCF data

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#83]
Hyeyoung provided information on all her files and found one session that had CCF data issue. 
A probe CCF was missing information, causing the packaging to fall back on PLaceHOlder silently. This messed up the ordering of probes in the NWB and disconnected the CCF alignment index.

**Comment by jeromelecoq** [comment]
Solution: 
1. is to add the missing probe data, reupload and reconvert . @Ahad-Allen will provide ETA to Hyeyoung. 
2. We discussed long term solution, and decided to have a script looping through the CCF file provided to make sure they are present. If not we would error out. This way, we would only bypass CCF registration when ALL probe data is not available.

**Comment by jeromelecoq** [comment]
Probe B was not inserted into the brain but not marked as failed. 
@Ahad-Allen will manually override the QC state and push processing then upload.

**Comment by Ahad-Allen** [comment]
The manual override worked and the re-upload worked! Moving to closed to mark this.
