### ISSUE TITLE
2 glow experiments are missing from Dandi

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#84]
Those experiments are missing CCF registration. @Ahad-Allen will reach out to Ben And Severine to get ETA for the files.

**Comment by jeromelecoq** [comment]
Waiting from Sev to perform registration, perhaps next week

**Comment by Ahad-Allen** [comment]
Contacted Ben and Sev about the CCF. Hoping to hear back soon :)

**Comment by jeromelecoq** [comment]
@Ahad-Allen to follow up with Sev

**Comment by jeromelecoq** [comment]
We apparently uploaded a lot more session this week to the excel sheet. Ahad was confused as to why so many. 
We need to follow up on teams.

**Comment by Ahad-Allen** [comment]
We have a meeting about this and some changes to older nice on Monday with Sev and Hannah.

**Comment by Ahad-Allen** [comment]
I met with Sev and Hannah yesterday about this and they shared a document showing all the sessions that need to be reuploaded and with corrected locations. I will work on the regeneration and upload of these today and then close the issue when they are up on dandi.

**Comment by Ahad-Allen** [comment]
Every session except for 1233182025 is converted! The d1 upload for this was not fully triggered, but ben has resolved this and says all the files should be up for it around 2pm. Once those are done, we can convert and we will have every single session for both projects!

**Comment by Ahad-Allen** [comment]
That file was converted and uploaded yesterday, we are done!
