### ISSUE TITLE
One session from Illusion needs a manual probe location fix

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#86]
Hyeyoung Shin
  [9:02 AM](https://openscope-allen.slack.com/archives/G014P5L3CD7/p1673283763636529)
Hi 
[@Ahad Bawany](https://openscope-allen.slack.com/team/U034QV5GMJ7)
, I think the CCF labeling and probe id in session sub_1183369803 is still problematic -- you mentioned that probe B was not inserted, but probe_id includes 1  ( nwb.general_extracellular_ephys_electrodes.vectordata.get('probe_id') ), and CCF labels include VISpm. Instead, it is missing probe_id 5, which corresponds to VISrl. I believe what happened here is that since probe B was missing, your program automatically assigned 0-4 to probes A,C,D,E,F; whereas the correct assignment would have been 0,2,3,4,5. Would you please correct this for me? Thank you...

Ahad Bawany
  [10:16 AM](https://openscope-allen.slack.com/archives/G014P5L3CD7/p1673288206790699)
Thanks for catching that Hyeyoung, I will work on getting that fixed!
New

Ahad Bawany
  [10:56 AM](https://openscope-allen.slack.com/archives/G014P5L3CD7/p1673290611498319)
ok, I think I've gotten to the root of the problem. Normally a probe like this would be marked as 'failed' and my code can handle that situation, but in this case it appears it wasn't, and I manually made it skip probeB during the initial input generation for the NWB file. The problem with this is that what I am actually doing is making it think probeC goes to 1 rather than 2. I should 'skip' probeB during the NWB writing rather than during the input gen
:+1:
2

Ahad Bawany
  [10:57 AM](https://openscope-allen.slack.com/archives/G014P5L3CD7/p1673290641132019)
I just need to do a little manual editing to the scripts for this one session and we should be good! I will try to get you that by end of day :slightly_smiling_face:

**Comment by jeromelecoq** [comment]
We think this is what is happening 



![Image](https://user-images.githubusercontent.com/2491343/211649725-db0444ce-0efa-466a-a94b-735577ba6347.png)

**Comment by Ahad-Allen** [comment]
I met with Hannah and she and Severine are working on looking into redoing the ccf for this one session.

**Comment by jeromelecoq** [comment]
One avenue to catch this earlier is to display brain areas assigned to each probe on OpenScope Data Portal. 
Let's discuss whether to include this at our QC meeting today

**Comment by Ahad-Allen** [comment]
We figured out that this is a problem related to the CCF alignment code and Corbett pushed a change to help fix all alignments for sessions with a failed probe. I will send Sev a list of all such sessions.
