### ISSUE TITLE
Hyeyoung looked over the new uploaded datasets and asked for clarification

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#98]
@Ahad-Allen to copy conversation here

**Comment by Ahad-Allen** [comment]
![Image](https://user-images.githubusercontent.com/87045911/217068391-900d7078-b64a-4aca-9bbf-b34b14c31b35.png)



![Image](https://user-images.githubusercontent.com/87045911/217068428-3c064a19-2803-4863-b6a8-a984ce6e7562.png)



![Image](https://user-images.githubusercontent.com/87045911/217068472-0dcb9f5c-ecb7-4080-8ef8-27928a36cda8.png)

**Comment by Ahad-Allen** [comment]
I've notified Sev about this and will update when possible.

**Comment by Ahad-Allen** [comment]
I pinged Sev for an update about this.

**Comment by Ahad-Allen** [comment]
Sev updated hyeyoung on this. This was a special label used for the session because the area was in vis, but in an unlabeled region.
