### ISSUE TITLE
Pop LFP field from NWB file during conversion

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/OpenScopeNWB#99]
Changes mentioned in issue #60 ought to be made

**Comment by jeromelecoq** [comment]
Let's check if it is a symlink . @Ahad-Allen .
If it is, we should make a feature suggestion to the AllenSDK team.

**Comment by Ahad-Allen** [comment]
The field is just a symlink, I can create a suggestion for the SDK team, but we should not have to do any work on our end at least :)

**Comment by jeromelecoq** [comment]
@Ahad-Allen to link the PR

**Comment by Ahad-Allen** [comment]
The issue associated with this is tracked at: https://github.com/AllenInstitute/AllenSDK/issues/2681

**Comment by Ahad-Allen** [comment]
I've scheduled a meeting with Adam on Wednesday to discuss how to handle the SDK issues and making PRs for all these unrelated tickets :)

**Comment by Ahad-Allen** [comment]
Sent some newly generated files to Carter for review.

**Comment by jeromelecoq** [comment]
Linked to #102 closing as duplicated?
